targets:
  $default:
    builders:
      generators|annotations:
        enabled: true

builders:
  generators:
    target: ":cubeExplorerBuilder"
    import: "package:cube_explorer/cube_explorer.dart"
    builder_factories: [ "cubeExplorerBuilder" ]
    build_extensions: { ".dart": [ ".g.part" ] }
    auto_apply: dependents
    build_to: cache
    applies_builders: [ "source_gen|combining_builder" ]