targets:
  $default:
    builders:
      generators|annotations:
        enabled: true

builders:
  generators:
    target: ":cubeExplorerBuilder" # Generator name
    import: "package:cube_explorer/cube_explorer.dart"
    builder_factories: ["cubeExplorerBuilder"] # Builder name(BuilderOption) this is a definition
    build_extensions: { ".dart": [".g.part"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]