class Case {
  Case({
    required this.scrambles,
    this.name,
    this.image,
  });

  static final twoCasesList = [
    Case(
      name: 'Generic 2Edge case',
      scrambles: [
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D U' F U R U R' U' F",
        "D' B L B' D U' F' L F' D F D' L' Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 R' F R U2 L F L' U F",
        "D' B L B' D U L' U2 L2 F2 L' F' Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 U2 R' F2 R U' D R U' R' D'",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D U2 F U R U R' L F2 L'",
        "D' B L B' D U' F' L F' L' U R U' R' Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 R U2 R' F' U F'",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D U' F U' R U' R' U' F",
        "D' B L B' D U F L F2 R' F R L' Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 U F2 U L F L' F",
        "D' B L B' D U' R' B2 L F' L' B2 R Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 U2 R' L F' L' F' R L F' L'",
        "D' B L B' D U2 F U R' D' F D F' R Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 U' R U' R2 F2 R U' L' U L",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D U2 R U' R' L F D F' D' L'",
        "D' B L B' D U2 L' U' L U2 L F' L2 U L Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 U2 R' F2 R U L' U' L",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D U' R' F R L F2 L' U L F L'",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D U2 L' F' U' F L U L F' L'",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D L' U' L U2 R U R' F'",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D F U' R U' R' U L F' L'",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D L F L' U R U R2 F R",
        "D' B L B' D U L' U2 L2 F2 L' F' Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 U' D R2 U' R2 D' F' U' F'",
        "D' B L B' D U L F' R' F R L2 U2 L Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 U' R F R U' R' F' U' R' F'",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D U' L F' L' U L D F D' L'",
        "D' B L B' D U' L F2 L' U L' U' L U F Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 U' R U' R' U' F' U F2",
        "D' B L B' D U R U' R2 F' R F' R U' R' F' Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 F' R F U2 F' R' F'",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D U L F' R' F R L2 U2 L",
        "D' B L B' D D R2 U' R2 D' L F' L' Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 L' U L U L F2 L2 U L",
        "D' B L B' D U2 D R F R' F' R U' R' D' Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 U' R F R U' R' F' U' R' F'",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D U2 L' U R L U' R' U' F'",
        "D' B L B' D L F D L' U' L D' F' L' Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 U2 R' F R L F' R' F R L'",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D U F R' L F2 R F' L'",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D U' L' U' L2 F2 L2 U L F",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D U R' F R L F' L' U2 L F L'",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D U R U2 R2 F R U2 R U R'",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D U' L F' L2 U R L U' R'",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D U F U2 L' U2 L2 F' L'",
        "D' B L B' D U' L F' L2 F' L U L' F L Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 U' F R' F' R U' F' R' F' R",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D U R' F R L F' L' U2 L F L'",
        "D' B L B' D U' L F R' L' F' R U' F' Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 U' R F R U' R' F' U' R' F'",
        "D' B L B' D U' F R' L F R F2 L' Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 U2 R' F R L F' R' F R L'",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D U R U' R2 F2 R2 U' R' U' F'",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D U2 R U' R' F' L F L' U F",
        "D' B L B' D D' L' U' L' U L2 D F' Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 U' F U' F L F L'",
        "D' B L B' D U R U2 R' U R U' R' L F L' Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 U2 L F2 D' L' U L D L'",
        "D' B L B' D U L' U2 L F L F L' U F Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 R U' R' U R U2 R2 F2 R",
        "D' B L B' D F U' R U' R' U L F' L' Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 U2 F' U' R' F' R L' U' L",
        "D' B L B' D U' L F' L' U L D F D' L' Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 U2 F L F L' U' L' U2 L",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D U R' F R U R' L F' L' F R",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D U' R U' R' L' U L U R' F' R",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D U' L F' R' F2 R F L' F",
        "D' B L B' D U R U' F U F' U' R2 F R Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 U2 R' F2 R L F' L' F",
        "D' B L B' D U' L U F L' F L U' F L' Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 U F U F' R' F R F2",
        "D' B L B' D U2 L' U R L U' R' U' F' Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 U2 R' F' R U' F R' F' R F'",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D U R U' R2 F2 R2 U' R' U' F'",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D U F' R' F' R F' U F'",
        "D' B L B' D U F R' L F2 R F' L' Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 U' R F U' F' R' F' R U' R'",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D U' F U' R U' R' U' F",
        "D' B L B' D U F' R U' R2 F R2 U R' Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 U' F R F U' F' R' U' F'",
        "D' B L B' D U2 L' U L U L F' L' F' Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 U F U F' R' F R F2",
        "D' B L B' D L' U' L U' R' F' R2 U' R' Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 U R F R' U R F' R' U' F'",
        "D' B L B' D U' R U' F R' F' R' D R D' Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 U2 F' R' L F2 L' F' R",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D U2 R U' R2 F' R F' L F2 L'",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D U' L F' R' L' F R U' F'",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D U' F R U2 R' U F",
        "D' B L B' D U L' U2 L F2 U F Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 U' R F R' U' R F' R' U' F'",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D U2 F U R' D' F' D F R",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D U' L F' L2 F' L U' L' F L",
        "D' B L B' D U' L F' L2 U R L U' R' Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 F' R U' R' F' U' F2",
        "D' B L B' D U F U' F' U' L F' L' Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 U' R U' R' U' L' U L2 F2 L'",
        "D' B L B' D L' U' L2 F' L' U' R' F' R Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 U2 F L U L F L' U' L'",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D U' L F' L2 F' L U' L' F L",
        "D' B L B' D D R2 U' R2 D' L F' L' Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 U2 R' F R L F' R' F R L'",
        "D' B L B' D U R D2 L' B' L D2 R' Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 U2 R' F2 R L F' L' U F",
        "D' B L B' D L' F' L U' L' F L2 F' L' Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 U2 R' F R U R U R' L F' L'",
        "D' B L B' D U F' U' F R U R' F Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 U F' U F L' U L F",
        "D' B L B' D U' F U' R U' R' U' F Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 U2 F L U L' F L U' L'",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D L F' D L' U' L D' F' L'",
        "D' B L B' D U2 R' F R U D R2 U' R2 D' Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 U2 R' F2 R U' D R U' R' D'",
        "D' B L B' D U R' U' F R2 U' R' U R' U R Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 U2 R' F R2 U' R' U2 L F' L'",
        "D' B L B' D U' L F' L' U' L' F' U' F L Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 U' D' L F' L2 F U L D",
        "D' B L B' D U2 L' U L2 F' R' L' F' R Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 U2 R' F2 R L F' L' U F",
        "D' B L B' D U R' F' L F L' F R Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 L' U2 L2 F L2 U L F",
        "D' B L B' D U' L F' D L' U L F' D' L' Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 U R U' R' U2 R U' R2 F2 R",
        "D' B L B' D U' R' L F L' F' R2 U' R' F' Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 U2 R' F2 R U' D R U' R' D'",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D U R' F' U' R F' R' U R F2",
        "D' B L B' D U' L F' L' U L' F' U' F L Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 F' U' F' R U' R' F2",
        "D' B L B' D U R' F' U' R F' R' U R F2 Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 U2 L F2 D L' U' L D' L'",
        "D' B L B' D U' L' U2 L F L' U L2 F' L' Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 F' R F U2 F' R' F'",
        "D' B L B' D U' R U' R' U2 R U' R' L F' L' Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 U2 F' U2 R U R2 F' R",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D U' R U' F R' F' R' D R D'",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D R' F R2 U R' U2 L F L'",
        "D' B L B' D U' R U' R' L' U L U R' F' R Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 U' F' U' L F L' U' F",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D U' R U' R' U' F' R U R2 F R",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D F U2 R U R' L F' L'",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D U' R U' R' U' F' R U R2 F R",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D U' R' B2 L F' L' B2 R",
        "D' B L B' D R U2 R' U L' U' L2 F' L' Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 R2 U2 R' L F L' F R'",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D D R2 U' R2 D' L F' L'",
        "D' B L B' D U' F' L F' L' F U' F' Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 U2 R' F2 R U L' U' L",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D U D' L' U2 L D F'",
        "D' B L B' D U' L F' L' U D R U R' D' Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 L' U2 L2 F2 L2 U2 L",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D U2 R U' R' U2 R' F' R L F L'",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D U' L F' D F L' U' L D' L'",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D L' U' L U L F L' F'",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D U' L U F L' F L U' F L'",
        "D' B L B' D U2 F R' F D' F' D F R Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 U F R' D R' D' R2",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D U' F' U' R U' R' U' F",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D U' L F' L2 F' L U' L' F L",
        "D' B L B' D U R' F D' F' R U2 R' D R Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 U2 F R' L F' R L' F",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D U F' R' F' R F' U F'",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D U' L F' L2 F' L U' L' F L",
        "D' B L B' D U' L F' D F L' U' L D' L' Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 U' L D L' U' L D' F2 L'",
        "D' B L B' D L' U' L2 F' L' U' R' F' R Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 L' U L U L F2 L2 U L",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D U' F U' R U' R' U' F",
        "D' B L B' D U' L F' L' U L' F' U' F L Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 U2 L F2 D' L' U' L D L'",
        "D' B L B' D U' L F2 L' U L' U' L U F Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 U2 F' R' D R' D' R2 F'",
        "D' B L B' D U' L' U L2 F R' F2 R L' Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 R' U' F' U R U2 F2",
        "D' B L B' D F U2 R U R' L F' L' Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 U2 R' F' R F' U2 R U R'",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D U R U' R2 F2 R2 U' R' U' F'",
        "D' B L B' D U2 F U R U R' L F2 L' Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 R U' R' U' R' F' R2 U' R' F'",
        "D' B L B' D U' F' L F2 L2 U L F Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 U2 R' D' F' D R2 U' R' F'",
        "D' B L B' D U2 L' U L2 F' R' L' F' R Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 U2 R' L F' L' F R L F' L'",
        "D' B L B' D U F' R' F' R F' U F' Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 U' F R U' R' F2 R U' R'",
        "D' B L B' D U' L F2 L' U L' U' L U F Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 U2 F U' L' U' L U2 F",
        "D' B L B' D F U' L F L' F2 Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 U2 D F R' F' R D' F",
        "D' B L B' D D' L' U' L' U L2 D F' Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 D R U' R' U' D' L F2 L'",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D U F U' F' U' L F' L'",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D U' L' U2 L F L' U L2 F' L'",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D D R2 U' R2 D' L F' L'",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D U2 R U' R2 F' R F' L F2 L'",
        "D' B L B' D U' R U' R' D R F R' F' D' Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 U F U F L' U L F",
        "D' B L B' D U' R U' R' U2 R U' R' L F' L' Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 U2 R' F' D' R U R' D R F'",
        "D' B L B' D U' L' U2 L F L' U L2 F' L' Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 U' F R U' R' F2 R U' R'",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D U R U2 R' U R U' R' L F L'",
        "D' B L B' D U2 R U' F2 R' F' R F' R' F' Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 U2 R' F2 R U' D R U' R' D'",
        "D' B L B' D U2 F U' R' D' F D F' R Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 U2 R' F2 R2 U' R' U R U' R'",
        "D' B L B' D U R' F D' F' R U2 R' D R Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 U R U' R' U F' R' F' R",
        "D' B L B' D R F' U R' U' F' R F2 R' Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 R' D R U2 R' D' F2 R",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D U' F L F' L' U R U R'",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D U F U2 L' U2 L2 F' L'",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D U' R U' R' D R F R' F' D'",
        "D' B L B' D U2 F R' F' D' F D F' R Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 U' F R' F U' F' U R F'",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D L F' D L' U' L D' F' L'",
        "D' B L B' D U' R' F R L F' D F D' L' Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 U L D' L' U L D F2 L'",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D U R U2 R' U R U' R' L F L'",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D U' F' U' R U' R' U' F",
        "D' B L B' D U' R' F D' F' D R L F' L' Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 U2 R' D' F' D R2 U' R' F'",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D U L F L' U2 L' U' L2 F' L'",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D U2 F R' F' D' F D F' R",
        "D' B L B' D U R' F' U' R F' R' U R F2 Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 R' D R U R2 D' R' U' R'",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D U2 R U' R2 F' R F' L F2 L'",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D F U2 R U R' L F' L'",
        "D' B L B' D F U' R U' R' U L F' L' Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 U2 L U L' F L U' F2 L'",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D U2 R U' R' L U F U' L'",
        "D' B L B' D U' L F' L2 U' L U' L' U2 L Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 U2 L F2 D' L' U L D L'",
        "D' B L B' D L' U' L U L F L' F' Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 U2 R' F2 U' F' U F R",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D L F D L' U' L D' F' L'",
        "D' B L B' D U2 F U L F' L' U L F' L' Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 U' L F L' U' R' F R2 U' R'",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D U F' R' D' F2 D F' R",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D F U' R U' R' U L F' L'",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D U' L F2 L' U L' U' L U F",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D L F' D' L' U' L D F' L'",
        "D' B L B' D U2 D R F R' F' R U' R' D' Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 U2 R' U' R F' R' U F' R F'",
        "D' B L B' D U F U' F' R U R' F Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 R U' R' U R U2 R2 F2 R",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D U2 R U' R' L F D F' D' L'",
        "D' B L B' D U' L D' L2 U L2 D F' L' Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 U' L D' L' U' L D F2 L'",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D U F R' L F2 R F' L'",
        "D' B L B' D U' F' L F2 L2 U L F Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 U' L D' L' U' L D F2 L'",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D R U' R2 L F L' F' R F'",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D U2 L' F' U' F L U L F' L'",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D U2 R U' F2 R' F' R F' R' F'",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D U2 F U R' D' F D F' R",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D U' L F' L2 F' L U L' F L",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D U' F L F L' F' U' F'",
        "D' B L B' D F U' R U' R' U L F' L' Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 L' U2 L2 F L2 U L F",
        "D' B L B' D U' F L F R' F2 R L' Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 R' U' F' U R U2 F2",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D U F' R' D' F2 D F' R",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D U' L F' D L' U L F D' L'",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D U' R' L F L' F' R U' R' F' R",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D U' R' L F L' F' L F L' F' R",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D U D' L' U2 L D F'",
        "D' B L B' D U2 D R F R' F' R U' R' D' Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 U' R' U' R F' R' U R U' F'",
        "D' B L B' D U2 L' U L2 F' R' L' F' R Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 U2 F' U' R U' R' U' F'",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D U R U' R2 F' R F' R U' R' F'",
        "D' B L B' D D' L' U' L U' D R' F' R Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 U' R U R' U2 R' F2 R",
        "D' B L B' D U' L F' L2 U' L U' L' U2 L Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 U2 R' F2 R L' F' U F L",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D U' F2 B L F' L' B'",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D U' L' U L2 F R' F2 R L'",
        "D' B L B' D D' L' U' L U' D R' F' R Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 U2 F' U' R' F' R2 U R'",
        "D' B L B' D U' R' F D' F' D R L F' L' Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 U F R' F' R L' U L F'",
        "D' B L B' D U2 R U' R' F' L F L' F Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 U' F U' R' F' R F' R U' R'",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D L F' L' U R U R2 F R",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D U2 L' U L U L F' L' F'",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D U R U2 R2 F' R L F L' F",
        "D' B L B' D U R U' F U F' U' R2 F R Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 U2 R' F R F R' F R",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D U2 L' U' L U2 L F' L2 U L",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D R F' U R' U' F' R F2 R'",
        "D' B L B' D R U R' U' R' F R F Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 U2 R' F' R F R' F' R U' F'",
        "D' B L B' D U2 R U' R' F' L F L' F Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 U R F U' R' U R F' R' F'",
        "D' B L B' D U2 F' U' L' U' L2 F2 L' Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 U2 R' F R2 U' R' U2 L F' L'",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D U' F R U2 R' U F",
        "Rw U2 Rw D Rw' U2 Rw D' Rw2' D' B L B' D U R U2 R' U R U' R' L F L'",
        "D' B L B' D U' L F R' F2 R L2 U L Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 U2 R' L F' L' F' R L F' L'",
        "D' B L B' D U F U R U' R' U' L F L' Rw U2 Rw D Rw' U2 Rw D' Rw2' D2 B2 D2 F' U2 F U' F",
      ],
    ),
  ];
  static final twoTwoCasesList = [
    Case(
      name: 'Generic two tww',
      scrambles: [
        "L F2 L' F' R' U' F' U R F' U F Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U R U R' U' R' F U' F' U R F",
        "L F2 L' U' R F R' U R F' R' F' R U2 R' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U R U2 R' D R F R' F' D'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U2 R2 U R' U2 D R' D' R U R2",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' R' U D' F2 U' D F2 U2 R",
        "L F2 L' U F U' R' F' U' F' U R2 U' R' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U2 F' U' F' R U R' F2 U' F'",
        "L F2 L' U' R' D R2 U' R U D2 F2 D Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U2 F' D R' B U' B' U' D' F",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' F' U D R U2 R' D' F'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U' R U' F U' F' R' U R' F2 R",
        "L F2 L' U F U' F' R U2 R' U R' F' R Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U2 R' D' F D F' D' F D F' R",
        "L F2 L' U F U' R' F2 R U R U R' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U2 R' F2 R F2 U R' F2 R F",
        "L F2 L' U' R2 U2 R' U2 R F' R U' D R' D' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U F' R U R' D' F U' F' D F",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U' R F R' U R F' R' F' R U2 R'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' F U' F U2 F U' F'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' F' U2 D R' U D' F' R U' R'",
        "L F2 L' U2 F U2 R' F' R U' F' R U2 R' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U2 R U' R2 F2 D R' D' R2 F'",
        "L F2 L' R U R' F' R F U' F' U' R' F' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U' R' F R D R2 D R' U' R D2",
        "L F2 L' U' F' R' F' R2 U' R' U F Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U R' F R2 U R' U2 R' F' R F",
        "L F2 L' U F U' R F U' F' R2 F' R F' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U' R U' R2 F' R F U2 R U2 R'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U' F' U F' U2 R' U R' F' R2",
        "L F2 L' U2 R2 U2 F' R' F' R2 U2 R2 Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' R U F R' U R F' U2 R2 F R",
        "L F2 L' U R2 F' U' F' R U R F' U R Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U2 R' F' R F U F2 R U R' F'",
        "L F2 L' U2 R' F' R F' R U2 R' F' U' F' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U2 R' F' R F U' F2 U2 R' F' R",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' F U' F U' F U2 F'",
        "L F2 L' U R U' F2 U' D' F2 U' D R' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' R F2 R' F' R U2 F' R' F",
        "L F2 L' F' U' R B R' F' R B' R' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U R F U' R' U R F' U R' F",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U2 F U2 F' U' F' R U2 R'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' R U' R' D R U' R U R2 D'",
        "L F2 L' U' F' U2 R F U' F' U R' F' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U2 R U R' U2 D R U' F R' F' D'",
        "L F2 L' U2 R U R2 U' R' D R U D' R Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U' R F' U' R' D' F' U' D R F R",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U R U' R U R' U R U2 R2 F2",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U2 R' F' R2 U' R2 F R U' F2",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U' R U R' D R2 U R' U R D'",
        "L F2 L' R U' D R2 U' D2 R U R' D R Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U D R B' R' D' R' D B R' D'",
        "L F2 L' U2 R2 U R U' R' U R' F2 Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U' R U' R' U2 R' F' R F' R' F2 R",
        "L F2 L' U2 R' F' R F' R U2 R' F' U' F' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U R U' R' U2 R' F' D' F' D R F'",
        "L F2 L' F' U' F' R2 U R2 U' R2 Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U2 R' F2 R D R2 U R' U' D' F'",
        "L F2 L' U2 F U F' U F' U2 F' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' R F U' R U' R F' R2 F R",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U' R' F' R2 U' R' U' F R U' R'",
        "L F2 L' U2 R U2 R2 F2 R2 U' R' U R U' R' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U R2 U2 R' U' R F' R2 F U' R2",
        "L F2 L' U' D R' D' F' D F R2 F' R D' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' R U' R' U2 D R U2 F R' F' D'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U2 R U R' F' R U' R' U F",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U' R U R' U' R U' R' U' F2",
        "L F2 L' U' F' D R U R U' R' U R D' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' F D R' U' F R2 F' U R D'",
        "L F2 L' U' F2 R2 D' F' D F R2 Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U R' F' R2 U R' U' F R U R'",
        "L F2 L' R' U' F R F' R' U F' R F' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U' R U2 R' U R U2 R' F' R' F R",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' F2 U' F U2 R U R' F'",
        "L F2 L' U F U' R' F' R F' U' R U' R' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U' R U' R2 F' R F U2 R U2 R'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U' F' U2 R' F U' F' U R F'",
        "L F2 L' U' D R U' R D' R2 U R2 U' R2 Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U2 R U R2 F R U D R U2 R' D'",
        "L F2 L' U D R U R U2 R2 U' R2 D' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U2 F' U' D B2 U D' R F R",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U R U R U2 R2 F2 R2 U2 R2",
        "L F2 L' U F U' R F U' F' R2 F' R F' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U' R' U' D' F' D R' F R U R",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' D R' U' B' R2 B R' U' R D'",
        "L F2 L' R' U' F R F' R' U F' R F' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' R U2 R2 F2 R F' R' F' R F'",
        "L F2 L' F2 U F U' R U' R' F' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U' R F R' U2 R2 U R' F' R' F'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U' F2 R2 D' F' D F R2",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' F' D R' U' D' F' U' R U2 R'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' R' F' R U D R U2 R' D' F'",
        "L F2 L' U2 R' F' R F D2 B2 D2 Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U2 R U R2 F R U D R U2 R' D'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' R2 D R2 U' R U' R D' R2",
        "L F2 L' U' F U F2 U F' U2 F Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U' D R B U' F' U' F B' R D'",
        "L F2 L' U' F' D R U R U' R' U R D' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U2 R F' U2 R2 F R2 U2 F R' F'",
        "L F2 L' R' U' F R F' R' U F' R F' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U' R' U' F' D R' D' F R U R",
        "L F2 L' U F U2 F' R U R' U F2 Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U' D R B U' F' U' F B' R D'",
        "L F2 L' U R U' R' U' D R2 U2 R' U R D' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U2 R U2 R' U D R F R' F' D'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U' F U' R' F2 R U2 F2",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U' F' R U R' U F' R U R' F'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U' D R' D' F' D F R2 F' R D'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U R' U' R F' R' U R2 U2 R' F'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U' D R U D' F U' F' D R D'",
        "L F2 L' F' U' R' U R' F' R2 F' U' F Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U2 F' U R2 F R D R2 D' R'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U2 F' U F U F R' F2 R F",
        "L F2 L' F' U' R B' R' F' R B R' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U' R F R U' R' U2 F' R' F'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U2 F U2 F' U' F' R U2 R'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' R' F2 R2 U2 F R' U R F' R'",
        "L F2 L' R2 D R2 U' R U' R D' R2 Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U2 R' F' R U F' D R2 U' D' F2",
        "L F2 L' F' U' F' R2 U R2 U' R2 Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U' R F2 U R' U' F' R U F' R' F'",
        "L F2 L' U F U' R' F' U' F' U R2 U' R' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U2 R U2 F2 R' F' R F' U' R2 F R",
        "L F2 L' U2 D R U' R' U2 R U2 R D' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U' F U D R U2 R' U2 R2 D'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' B R2 B2 R2 F' B' U' F'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U' R U' R2 D R U R U' R2 D' R",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U2 R U R' U' R U R' U' D R2 D'",
        "L F2 L' U' F' D R U F' U' F R D' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U' F U' R U R' F' U F'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U R U' R' U' D R2 U2 R' U R D'",
        "L F2 L' U2 R U' R' U2 D R2 U R' U R D' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U2 R U2 R' F' R' U' F U R",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' F2 U F U' R U' R' F'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U2 R U2 R2 F' D' F2 D F R",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U2 F U2 F U' F2 U' F'",
        "L F2 L' R' F' R2 U R' U' R U' R' F' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U2 R' U F U' B' R2 B U R",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U R F2 R' F' U' R F' U' R2 F' R",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' R U' R' F' U' R' F D' F' D R",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U' D R B' R2 B U' R2 U R' D'",
        "L F2 L' R U2 R' F2 U2 F2 Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U2 R U R' U2 F' U2 R' F R",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' R' U D' F2 U' D F2 U2 R",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U R U R' U' F' R F U' F' R' F'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U R' D R U' R' D' R F' U' F'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U' R U R' U R U R' U' F2",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' F U' F' U' R U R' U F2",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' R' F2 R2 U' R2 D' F2 D R",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U' R U2 R2 F' R U' R' F R2 U2 R'",
        "L F2 L' F' U' R B' R' F' R B R' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U2 F' U' R U R' U F R U2 R'",
        "L F2 L' R' U R2 U' R' F' R' U' R F' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U2 R U R2 F R U D R U2 R' D'",
        "L F2 L' F' U D R U2 R' D' F' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U' R' F' R F R U' R2 F' R F",
        "L F2 L' U' R2 U2 R' U2 R F' R U' D R' D' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' D R' U D' F2 R U R' F",
        "L F2 L' D R' U' R U R D' F' U' F Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' F U' D R' F R F' R2 D'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U2 R' F' R U F U F' U2 F'",
        "L F2 L' U2 R U2 R' F' U' R U' R' U' F' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U' F D R2 U2 R' U R' D' F2",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' F2 U' F U2 R U R' F'",
        "L F2 L' R' F2 R2 F U2 R' U R F' R' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' R' F' R2 U' F R U F' R' F'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U2 R U R2 F2 D' F D F' R",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' R2 D R2 U' R U' R D' R2",
        "L F2 L' U' R' D R2 U' R U D2 F2 D Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' R U R' U R' F R U R U2 R'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U' D R U' R U' B2 U D' R2",
        "L F2 L' U F U2 F' R U R' U F2 Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U2 R U F U2 F' R2 F R2 U R'",
        "L F2 L' R2 U R2 F U' F' U' F' R U R Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U' R F2 R2 F' R U2 R U' F' R' F'",
        "L F2 L' F' R U' R' F U' D R2 D' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' R U R' U R' F R U R U2 R'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U2 B' U' F' R2 F R' U R' B",
        "L F2 L' R' U D' F2 U' D F2 U2 R Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U' R2 D2 R' U' R B' D2 R' U R'",
        "L F2 L' U' D R' D' F' D F R2 F' R D' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U2 F' U' R U R' F' U' D R2 D'",
        "L F2 L' R' F' R' U' F' U R2 F' U' F Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' F U' D R' F R F' R2 D'",
        "L F2 L' U R U R U2 R2 F2 R2 U2 R2 Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U' R F R' F' U2 R' D R D'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' R' F' R' U R2 U2 F' U R2",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U' R U F U2 R' U R' F' R2 F' R",
        "L F2 L' U2 R2 U2 R' F' R U2 R2 U F' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' R U2 R2 U R F R' U' R",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' R' F' R D R' U2 R U' D' F'",
        "L F2 L' U R U R U2 R2 F2 R2 U2 R2 Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U' R F R U' R2 U2 R F' R' F'",
        "L F2 L' R2 D R' U2 R U R2 U' D' R2 Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U' R U2 R' U R' F R U R U2 R'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U R U' R' D R2 U' R' U' R' D'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U' R' F R F' R' D' F D F' R",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U2 R U2 R' U R U' R' U' D R2 D'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U' F' U2 F' U' F' R' F' R",
        "L F2 L' U2 D R U D' F' U F' R' F' R Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' R2 U R' U R U2 R2 F R U' R'",
        "L F2 L' F U' F U2 F U' F' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U2 R U R' U2 F' U2 R' F R",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' R' U D' F2 U' D F2 U2 R",
        "L F2 L' U2 F R' F' R U2 F' U2 F' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U' R U R' U F' R U R' F",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U2 R2 U2 R' F' R' U F' U R2",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' F' U' F' R2 U R2 U' R2",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U R U' R' U' D R' U' R2 U R D'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U' D R U' R U B2 U D' R2",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U R U' D R2 D' R F' R' U' R F'",
        "L F2 L' U' F2 R2 D' F' D F R2 Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U R' F R U F' R U2 R2 F R",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U' R U' R' D R2 U' R2 U D' F2",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U2 R' F' R' U2 F R2 F' U2 R2 F",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' R' D' F D F2 R2 U' R' F'",
        "L F2 L' U' R' D R U R' D' R F' U' F' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U2 F' U' F' R U R' F2 U' F'",
        "L F2 L' R' F' R U' F' R F R2 F' R' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U' R F R U' R' U2 F' R' F'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U' R D R U' D R' U R D2 R",
        "L F2 L' U2 F' U' F' U' F2 R U2 R' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U' F U' R U R' U R U' R' F2",
        "L F2 L' U2 R2 U2 R' F' R2 U2 R2 U' F' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' R' F' U' R' F R U F' R F'",
        "L F2 L' F' R U' R2 F' R U2 R U2 R' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' R U R' D R U' F' U' F R' D'",
        "L F2 L' R' U' F R F R' U F2 R Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' F D R' U' F R2 F' U R D'",
        "L F2 L' R2 D R' U2 R U R2 U' D' R2 Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U R U' R' U2 R U2 R' F' R' F R",
        "L F2 L' U F U' F' R U2 R' U R' F' R Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U2 R U R' U R U' R' F R U' R'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U' R2 U R2 D R2 U' D' R' U' R'",
        "L F2 L' U' F' R' F' R2 U' R' U F Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U2 R' U' F' U R U F' U2 F2",
        "L F2 L' R U' R' U' F' U' R U R2 F R Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U2 R U2 R2 F R U D R U2 R' D'",
        "L F2 L' U' R' U' D R' D' R U R2 U' R' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U' R U2 R' U R' F R U R U2 R'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U' F U F' U' R' F' R2 U' R'",
        "L F2 L' U R U R U D R2 U' D' R2 Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U D R U F' U F U2 R' D'",
        "L F2 L' R2 D R' U2 R U R2 U' D' R2 Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U2 R' D' F2 D R U2 R U' R' F'",
        "L F2 L' U' F' D R U' F' U' F R D' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' R U2 R2 U' F' U R U F",
        "L F2 L' U' R U' R' U F' R U R' U' F' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U2 D R F' R2 F' R2 F D' F",
        "L F2 L' F' R' U' R U' R' U2 R U F' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U' R U F U2 F' U R' U' R' F R",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' R U' R' U2 R U R' U' D R2 D'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U2 R' F' R F' R2 U2 F2 U2 R2",
        "L F2 L' R' F2 R2 U' R2 D' F2 D R Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U' F U R U2 R' U' F2",
        "L F2 L' U' F' R' U R' F' R D R' D' R2 Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U' F' U F' R' F' R U F2",
        "L F2 L' U2 D R U2 R' U' R U R D' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U' R2 D2 R' U' R B' D2 R' U R'",
        "L F2 L' F' R U2 R' U D R' U D' F' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U' D R2 F R' F' R' U' R D'",
        "L F2 L' U F U' F' D R D' R U' R' F' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U' R F R U2 R' U' F' U' R' F'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U2 R U' R' U2 D R2 U R' U R D'",
        "L F2 L' F2 U2 R F R' U R F' R' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U R U' R' U D R U2 F R' F' D'",
        "L F2 L' U2 D R U2 R' U' R U R D' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' R F2 R' F' R U2 F' R' F",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U' D F' R2 F' R2 F R2 D'",
        "L F2 L' U2 R U' R' U' R' F' R2 U' R' U' F' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U2 R' D' F D F' D' F D F' R",
        "L F2 L' U R U2 R' F' U' F' R' F R Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U2 R' F' R U F' U D2 B2 D2",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' R U F U' F' U' R' F' R U R'",
        "L F2 L' R' F2 D' F2 D R U' R U' R' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' R U2 R' F' R' U' F' U F2 R",
        "L F2 L' D2 R' U' R2 B R' U' D' R D' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' R' U' R' F R U R F' U' F'",
        "L F2 L' U' D R U D' F U' F' D R D' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U2 B' R' F R F R' F' R B",
        "L F2 L' U2 D2 R' U R D' R D' R U' R' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' D R U2 F' U F U2 R' D'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U' R U R' U' R U' R' U' F2",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U R U2 R' F' U' F' R' F R",
        "L F2 L' F' U R U' R' U R U2 R' F' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U' F' U' F2 R U R' F' U' F'",
        "L F2 L' U2 F' U D' F U F' D F' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U2 R U2 R2 F2 R F' U' R U R'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' R U2 R' F2 U2 F2",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' R' F2 R2 U2 F R' U R F' R'",
        "L F2 L' R U R' U2 R U' R' D R2 D' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U2 R U2 F2 R' F' R F' U' R2 F R",
        "L F2 L' U2 D R U D' F' U F' R' F' R Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U F' R U R' D' F U' F' D F",
        "L F2 L' U2 R' F' R U F U F' U2 F' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' R U2 R' D R U F R' F' D'",
        "L F2 L' R' F' R U' F2 R' F2 R F Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U R' F' R2 U R' U' F R U R'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U D R' U2 R U2 R2 U R' D'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U' D R U' R U' B2 U D' R2",
        "L F2 L' U' R U F U2 R' U R' F' R2 F' R Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U R2 U R2 F' R F R U' R2",
        "L F2 L' F' U' R B R' F' R B' R' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U2 R U2 F U F' R2 F R2 U2 R'",
        "L F2 L' R U' R' D R U' R U R2 D' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U' R2 D2 R' U' R B' D2 R' U R'",
        "L F2 L' R' F2 D' F2 D R U' R U' R' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U' R' F D R2 U2 R D' R' U R'",
        "L F2 L' U R' F' R F' U' F2 U' R U' R' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U R U2 F R' U R F' U' R' F",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' R F' U2 R2 B' R2 B U R' F'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' R' F' R' U R2 U2 F' U R2",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U2 R U R2 F2 D' F D F' R",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' R U R' U' R U R' U' F' U' F'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U R U R' U' D R2 U2 R2 D'",
        "L F2 L' U R U R' U' D R2 U2 R2 D' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U' F U' D R D' R' D R' D' R2",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' R U R2 F' R U' F' U' R' F' R",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' F R' U' R F2 R' U R F'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U' D R U' R D2 R2 U' D B2",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U' F' D R' U' R U R' U' R2 D'",
        "L F2 L' U2 R U' R' U2 D R2 U R' U R D' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' R2 U R' U R U2 R2 F R U' R'",
        "L F2 L' U R U' R' U' D R' U' R2 U R D' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U' F R U' R2 U D R2 U' D' R'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U D R' D' R2 U R U' R2 U' F2",
        "L F2 L' U' R2 U2 R' U2 R F' R U' D R' D' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' R' F' R D R U2 R' U D' F",
        "L F2 L' U' R' D R2 U' R U D2 F2 D Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U2 F' U' D B2 U D' R F R",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' R' F' U2 R B2 U' F' U B2",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U2 B' R' F' R F B U2 F2",
        "L F2 L' U' D R F' U2 R' F' R F R D' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' R' F' U' R' F R U F' R F'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U F' R U R' U' F' U' R' F2 R",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' B R2 B2 R2 F' B' U' F'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U2 R' F2 R2 U' R' U' F' U2 F'",
        "L F2 L' U' R U2 R2 F' R U' R' F R2 U2 R' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U2 F' U' R2 U' R' U2 R' U' F R2",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' R' U D' F2 U' D F2 U2 R",
        "L F2 L' R U F U' F' U' R' F' R U R' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U' F R U2 R' U2 D R U' R D'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U F' R U R' U' F' U' R' F2 R",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' D R' U' B' R2 B R' U' R D'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U2 R' F' R F D2 B2 D2",
        "L F2 L' U2 R U R' U R' F' D' F D R F' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U R U F R2 F' R F R U' R",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U2 R U R' U D R U' R' U R2 D'",
        "L F2 L' F U' F' U' D R U R D' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U2 R U R' U R U' R' F R U' R'",
        "L F2 L' U R' F2 R U' F' R U2 R2 F' R Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' D R U2 F' U F U2 R' D'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U2 B' R' F' R F B U2 F2",
        "L F2 L' U' F' D R2 U2 R' U2 R D' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U' R U' R2 F' R F U2 R U2 R'",
        "L F2 L' R' F' U2 R B2 U' F' U B2 Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U' R F R U2 R' U' F' U' R' F'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' R' U' F' U D R' D' R2 F2",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U2 R' F' R' U2 F R2 F' U2 R2 F",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U2 R U R' U' D R U R U' R2 D'",
        "L F2 L' R U F U' F' R' U' F' R U' R' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U R U R' U R' U' F' U R U F",
        "L F2 L' F' U' R B' R' F' R B R' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U R F U' R' U R F' U R' F",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' R U2 R' F2 U2 F2",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U2 F U2 F' U' F' R U2 R'",
        "L F2 L' F' U' R' U R' F' R2 F' U' F Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U' R' F2 R2 U' R' D R U D' F",
        "L F2 L' U R U R' U' D R2 U2 R2 D' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U2 F' R' F U2 R U R' U R",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U' R U2 R2 F' R U' R' F R2 U2 R'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U R U' R U R' U R U2 R2 F2",
        "L F2 L' F2 U2 R F R' U R F' R' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U R U' R' U2 R' F' D' F' D R F'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U R U' R U R' U R U2 R2 F2",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' R U R2 F' R U' F' U' R' F' R",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U' R F R' U R F' R' F' R U2 R'",
        "L F2 L' U R' F' R F' U' F2 U' R U' R' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U2 R U' R2 F2 D R' D' R2 F'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U2 R2 U2 R' F' R' U F' U R2",
        "L F2 L' U' R U2 R' U R' F' R2 U R' U' F' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U F2 R U R' F2 U' F'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' R F U' F' U R' U' R' F' R F'",
        "L F2 L' U2 F U2 R' F' R U' F' R U2 R' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U F' U' R U2 R' U F R U R'",
        "L F2 L' U2 R2 U R U' R' U R' F2 Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U' F' U' F' R' F' R U F2",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U D R' D' R2 U R U' R2 U' F2",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U2 D R U2 R2 U' R' U R' D'",
        "L F2 L' U' R2 U2 R' U2 R F' R U' D R' D' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U R F U' F' R' U R U R' F",
        "L F2 L' U2 R2 U2 R' F' R' U F' U R2 Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U2 R F U' R' U' R F' U R' F",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U R U2 R' F' U' F' R' F R",
        "L F2 L' U R U' R2 D R U' R2 D' R' U' R' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' R U' R2 F' R F' D R U D' F",
        "L F2 L' U' R U2 R' U R' F' R2 U R' U' F' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U' R U2 F R' U R U2 F' R2 F R",
        "L F2 L' R' F' U2 R B2 U' F' U B2 Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U2 R' F' R F U2 F2 U' R' F' R",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U R U R2 U D R2 U' D' R'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' R U' R' U' F' U' R' F R2 U R'",
        "L F2 L' U F U' R F U' F' R2 F' R F' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U2 R F U' F' R' U' R U R' F",
        "L F2 L' R' U' F' U D R U' R2 D' R2 Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U2 R' F' R U2 F U2 R' F' R F'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U2 R U2 R2 F R U R U' R' F",
        "L F2 L' U2 R2 U' R2 U' R F' U' R' U' F' R2 Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' R U2 R' U R' F' R F' R' F2 R",
        "L F2 L' U' D F' R2 F' R2 F R2 D' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' R U2 R' D R U F R' F' D'",
        "L F2 L' U2 R U2 R2 F' D' F2 D F R Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U' R U' R D2 B' D2 R' U R'",
        "L F2 L' D R' U' B' R2 B R' U' R D' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U F' U R2 D R D' R U F",
        "L F2 L' F2 R F R' U' R F' R' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' R' U' R' F R U R F' U' F'",
        "L F2 L' U R U' R' U' R U' R' D R2 D' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U' F D R2 U2 R' U R' D' F2",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' F' D R' U D' F2 U2 F",
        "L F2 L' U2 B' U' F' R2 F R' U R' B Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U R U R' U R' U' F' U R U F",
        "L F2 L' U D F' U2 F R2 D' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U2 D R U2 R' U R F R' F' D'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' R' F2 R2 U' R2 D' F2 D R",
        "L F2 L' F U' F' U' R U R' U F2 Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U' D R F R U R2 U' F' R2 D'",
        "L F2 L' U R' D R U' R' D' R F' U' F' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U2 R U' R2 F R U' R B U B' R'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U2 R U2 R' U R U' R' U' D R2 D'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U' F D R' U' R U D' R' F2 R",
        "L F2 L' F' U' R' U R' F' R2 F' U' F Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' R U R' U R' F' D' F D F R",
        "L F2 L' U' R2 U R2 D R2 U' D' R' U' R' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' R U' R' U2 D R U2 F R' F' D'",
        "L F2 L' F' U' R B R' F' R B' R' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U2 R' F2 R D R2 U' R2 U D' F'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U2 R' D R U2 R2 D' R2 F' U' F'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' R U R' U' R U R' U' F' U' F'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U' B' D R2 D' B R U' R'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U F U2 F' D R U R D'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U' F' D R' U' R U R U' R2 D'",
        "L F2 L' R U2 R U2 R2 F2 U2 R2 Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U R' F R U F R' F2 R U' F'",
        "L F2 L' U' F' R' U R' F' R D R' D' R2 Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U R U' F U' R' U' R F' R2 F R",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U' R' D R U R' D' R F' U' F'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' R' F' R F' R U2 R' F U' F'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U' F U F' U' R' F' R2 U' R'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U2 F' U F U F R' F2 R F",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U R U' R' U' R U' R' D R2 D'",
        "L F2 L' U R' F R2 U2 F U F' R2 F' R Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U R U2 R' U' F' D R' U D' F",
        "L F2 L' R U F U' F' R' U' F' R U' R' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U' F U D R2 U R' U R' D' F2",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U2 R' F' R' U2 F R2 F' U2 R2 F",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' D R' U' R U R D' F' U' F",
        "L F2 L' F U F2 U2 F R' F2 R Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U R U' R' U2 R' F' D' F' D R F'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U F U' F' D R D' R U' R' F'",
        "L F2 L' U D R' D' R2 U R U' R2 U' F2 Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U2 R F' U2 R2 F R2 U2 F R' F'",
        "L F2 L' U' R' D R2 U' R U D2 F2 D Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U2 R' F' R U F' U D2 B2 D2",
        "L F2 L' U2 D2 R' U R D' R D' R U' R' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U' R U R' U' F R U R' F' U' F'",
        "L F2 L' U2 R' F' R' U2 F R2 F' U2 R2 F Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U2 R' F' R U2 F U2 R' F' R F'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' R' F' R U' F2 R' F2 R F",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U2 R U' R' U' D R2 U' R' U2 R' D'",
        "L F2 L' U2 R U' R' U2 D R2 U R' U R D' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' D R U2 R' U D' F R U' R'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U D R' D' R2 U R U' R2 U' F2",
        "L F2 L' R U' D R2 U' R U' R' D' R Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U2 R U2 F U F' R2 F R2 U2 R'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U2 R2 U2 R' F' R2 U2 R2 U' F'",
        "L F2 L' U' R' D R2 U' R U D2 F2 D Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U' F U' R U R' F' U F'",
        "L F2 L' U R' F R F' U2 D R U' R D' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' R F' U D R U' D' F U2 R' F",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U' R U' R' D R2 U' R2 U D' F2",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U R U R' U' R' F U' F' U F' R",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U' F2 R2 D' F' D F R2",
        "L F2 L' U D R' B R U' D' F' R' U F' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U2 R' F U' R2 F R2 F' R2 U R",
        "L F2 L' U2 R2 U2 R' F' R2 U2 R2 U' F' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' R' F' R2 U' F R U F' R' F'",
        "L F2 L' F' U' R B' R' F' R B R' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U2 R U' R2 F R U' R B U B' R'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' R' F' R D R' U2 R U' D' F'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' R U' R' U2 R U R' U' D R2 D'",
        "L F2 L' U2 D R U D' F' U F' R' F' R Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U' F R' U F' D' F U' D R F'",
        "L F2 L' U' F' D R U' F' U' F R D' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U R U R2 F' R F U' R U R'",
        "L F2 L' U' D R F R U R' U' F' R D' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U2 R' F U' R2 F R2 F' R2 U R",
        "L F2 L' U2 R2 U' R2 U' R F' U' R' U' F' R2 Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U' R' F2 R2 U' R' D R U D' F",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U2 F' U F U F R' F2 R F",
        "L F2 L' U' D R F R U R' U' F' R D' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U' D R2 F R' F' R' U' R D'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' F2 U F U' R U' R' F'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' F' R U2 R2 F' D' F D R",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U D R' D' R2 U R U' R2 U' F2",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U F' R U' R' U' F' U F2",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U2 R' F2 R2 U' R' U' F' U2 F'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' R' F' R U' F' R2 U R2 U' R2",
        "L F2 L' U F' R U R' U' F' U' R' F2 R Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U2 R' U' F' U R U F' U2 F2",
        "L F2 L' U R U R' U' F' R F U' F' R' F' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U2 D R F' R2 F' R2 F D' F",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U2 B' R' F' R F B U2 F2",
        "L F2 L' U2 F' U D' F U F' D F' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U R U' R' U2 R' F R U R U2 R'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U' D R B' R2 B U' R2 U R' D'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U' B' D R2 D' B R U' R'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' R' F2 R U' R U R' F U' F'",
        "L F2 L' U2 R U R' U' R U R' U' D R2 D' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U' F U2 R' F2 R2 U R2 F2 R",
        "L F2 L' U2 R2 U2 F' R' F' R2 U2 R2 Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U' R U' R D2 B' D2 R' U R'",
        "L F2 L' U' R U' R2 D R U R U' R2 D' R Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U' F R U F U' F' R' F2",
        "L F2 L' U D R2 U2 R2 U D' F' U' F Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U2 R' F' R U2 F U2 R' F' R F'",
        "L F2 L' U F U' R' F2 R U R U R' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U' R U' R' D R F' U F U2 R' D'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' R F' U2 R2 B' R2 B U R' F'",
        "L F2 L' U' F' D R U R U' R' U R D' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U F' R U R' D' F U' F' D F",
        "L F2 L' U2 F' R F R' U2 R F' R' U' F' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U2 R U R2 F R U D R U2 R' D'",
        "L F2 L' F2 R F R' U' R F' R' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U R' F R U F R' F2 R U' F'",
        "L F2 L' U2 B' R' F' R F B U2 F2 Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U2 R F' U' D R2 D' F' R2 F2 R",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U2 R' F' R2 U' R2 F R U' F2",
        "L F2 L' R' F2 R F' R' F R U' F Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U' F' U F' R' F' R U F2",
        "L F2 L' U2 F' U D' F U F' D F' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' R U2 R' U R' F' R F' R' F2 R",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U F' R U R' U' F' U' R' F2 R",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U R U2 R' F' U' F' R' F R",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U R F U R U' R' F' R' U' F2",
        "L F2 L' F' D R' U2 R U' D' F' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U2 F' U' R U R' U F R U2 R'",
        "L F2 L' R' U' F R F R' U F2 R Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' D R' D' F' U' F R U R' F2",
        "L F2 L' R F' U2 R2 B' R2 B U R' F' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U' F R U2 R' U2 D R U' R D'",
        "L F2 L' R F U' F' U R' U' R' F' R F' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U2 D' R' F B D' F' B' R D",
        "L F2 L' D2 B2 D2 F' U' F' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U2 R' F D' F' D R' U R2 U' R2",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U' F' D R U' F' U' F R D'",
        "L F2 L' U2 R U R' U D R U' R' U R2 D' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U2 F' U' F R U R' F R U' R'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U' F U F' R' F' R U' R U' R'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U R' F R U2 F' D R U R D'",
        "L F2 L' U F' R U' R' F' U' F' R U' R' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U R U2 R' U' R' F D' F' D R",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U F U2 F' R U R' U F2",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U2 R U R' U R' F' D' F' D F R",
        "L F2 L' U2 R' F' R U F U F' U2 F' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' F D R' U' F R2 F' U R D'",
        "L F2 L' U2 R2 U2 F' R' F' R2 U2 R2 Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U F2 R U R' F2 U' F'",
        "L F2 L' U2 R U R' U R U' R' U D R2 D' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' R' F' U' R' F R U F' R F'",
        "L F2 L' U' R2 U R2 D R2 U' D' R' U' R' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U' R U R' U2 F' R' F R",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' R' F' R F' R U2 R' F U' F'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U D R' U R2 U' R' U2 R2 D'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' R U' R' U F' R U' R' F",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U' F' D R2 U2 R' U2 R D'",
        "L F2 L' U2 F' U F U F R' F2 R F Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U2 R U2 F U F' R2 F R2 U2 R'",
        "L F2 L' U2 R U' R' U2 R' F' R2 U' R' F Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' R U F R' U R F' U2 R2 F R",
        "L F2 L' F' U' R B R' F' R B' R' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U' R F R U2 R' U' F' U' R' F'",
        "L F2 L' U R' F' R F R U' R' F' U' F' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U' R U' R2 F' R F U2 R U2 R'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U' R U R' D R2 U R' U R D'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' R U2 R' F2 U2 F2",
        "L F2 L' U R' F' R F R U' R' F' U' F' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U R U' R' U2 R' F R U R U2 R'",
        "L F2 L' F' U' F' R2 U R2 U' R2 Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U2 R2 D R2 U' B R U D' R'",
        "L F2 L' U' F U F2 U F' U2 F Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U2 R U F U' F' R' D R' U D' F",
        "L F2 L' U D R' U2 R U2 R2 U R' D' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' R F' U D R U' D' F U2 R' F",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U' R U' R' U' R' U D R2 U' D' R'",
        "L F2 L' R F U' F' R' F' R U R' U' F' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U R U F R' U R F' R' U' F",
        "L F2 L' U' F D R' U' R U D' R' F2 R Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U2 R' F' R U F' U' D R2 D' F2",
        "L F2 L' U' F D R' U' R U D' R' F2 R Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U2 F' U' R U R' U F R U2 R'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' F U' F U' F U2 F'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U' F U' F U F' U F2",
        "L F2 L' F' R2 U' F' U R2 F' U' F Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U2 R' F R U2 F' U' F R U2 R'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U' F' U R' F R F2 R' F R",
        "L F2 L' U2 F' U D' F U F' D F' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U2 F' U' R2 U' R' U2 R' U' F R2",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U R' F' R F' U' F2 U' R U' R'",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' F' U' R' F D' F' D F' R",
        "Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F2 L' U' F' U2 R' F U' F' U R F'",
        "L F2 L' U2 F' U D' F U F' D F' Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U F U R' F' R U' F U F2",
        "L F2 L' R' U' F2 R F' R' U F2 R Rw2 F2 Rw2 U' Rw2 F2 Rw2 L F L' U2 F' D R' U' D' F U' R U2 R'",
      ],
    ),
  ];
  static final threeCycleCasesList = [];

  final List<String> scrambles;
  final String? name;
  final String? image;
}
