const _rawInput = '''
R B' U B2 U B' U' R' U' 
R B U2 B2 U' B U' R' U' 
R F U2 R2 U' F' U2 R' U' 
R F U' R2 U2 F' U2 R' U' 
R U' B2 U' B U B2 R' U' 
R' F2 U F U' F2 U' R U' 
R F U R2 F' R2 U2 R U' 
R U' B U' B' R2 U R U' 
R' U F' U' F2 U' F' R U' 
R D' F D2 U' B D' R U' 
R F D2 L2 U' B D2 R U' 
R' U2 B' U2 R2 U' B R U' 
R D2 F L2 D2 U' B R U' 
R U2 R2 B' R2 U B R U' 
R U2 R2 B' U R2 B R U' 
R' F D R2 D' U' R' F' U' 
F2 R' F U F2 U2 R F' U' 
R' F U F2 U2 F2 R F' U' 
R F D2 U' B D2 R F' U' 
R' F U' R D2 B2 D2 F' U' 
R' F U' R U2 F2 U2 F U' 
F' R' U F' U2 F' R F U' 
L U2 L2 B U' L U2 B' U' 
U2 B U' L U L' U B' U' 
B R B' U2 B' U R' B' U' 
B R U' B' U' B' R' B' U' 
U2 B U2 R U' B2 R' B' U' 
U2 B' U R' U R U' B U' 
U2 B' L' B2 U' L U2 B U' 
U2 B' L' U' B2 L U2 B U' 
U2 B D L' D' B2 U B U' 
R' F U' R' B' F' R2 B U' 
U2 B U B2 D' R' D B U' 
F R' F' R U' R U R' U2 
U' R U' B U B' U R' U2 
U' R U2 F U' R2 F' R' U2 
B U' B R B U2 B R' U2 
U' R' U F' U F U' R U2 
U' R' B' R2 U' B U2 R U2 
U' R' B' U' R2 B U2 R U2 
U' R D B' D' R2 U R U2 
F' U F U' F R' F' R U2 
B U' B' R2 F R F' R U2 
U' R U R2 D' F' D R U2 
U F' D' L D F2 U' F' U2 
U F L F2 U L' U2 F' U2 
U F U' R U' R' U F' U2 
R U' R' U R' F R F' U2 
B U' B' F D R' D' F' U2 
U F' U' F2 D R D' F' U2 
R' F R F' U F' U' F U2 
U F' U L' U' L U' F U2 
L' U L2 F' U L' U2 F U2 
U F' U2 R' F2 U R F U2 
U F' U2 R' U F2 R F U2 
F' U2 L U' F L2 U' L U2 
F D R D' B F' U B' U2 
R B' U2 B' R' B' U B' U2 
R' F R' F' R2 B U B' U2 
R F R U R U F' R' U 
R F U' R U2 R F' R' U 
F' R' F2 U' R F2 U2 F' U 
F' R' U' F2 R F2 U2 F' U 
F' U' F2 R U R' U F' U 
F R2 U' R' U R2 U F' U 
F U R' U R2 U2 R' F' U 
F U R U' R2 U' R F' U 
F' R' D2 U B2 L' D2 F' U 
F' D R' D2 U L' D F' U 
F' U2 F2 L F2 U' L' F' U 
F U2 L U F2 U2 L' F' U 
F U2 L U2 F2 U L' F' U 
L F' D2 R' D2 U L' F' U 
F' D2 R' U B2 D2 L' F' U 
F' L U L2 U L U' F U 
F' R' U F2 U2 R U2 F U 
L F' L2 U2 L2 U' L' F U 
L' U2 L2 U2 F' U L' F U 
L D2 R2 D2 F' U L' F U 
R' F2 L R F U L' F U 
L F D U F2 D' L' F U 
F' U L2 U L' U' L2 F U 
U2 L' D' B D L2 U' L' U 
U2 L B L2 U B' U2 L' U 
U2 L U' F U' F' U L' U 
U2 L' U' L2 D F D' L' U 
L F' U2 L2 U' L' F L2 U 
U2 L' U B' U' B U' L U 
L' F' L U2 L U' F L U 
U2 L' U2 F' L2 U F L U 
U2 L' U2 F' U L2 F L U 
R U2 B' U R' B2 U2 B' U 
F R' F2 U F U2 R2 U' R' 
U F U2 R' U F' R2 U2 R' 
F R' F' D' F2 D R2 U2 R' 
L F' U L' F U' R U2 R' 
B U' B' R F R2 F' U2 R' 
F R2 F' R' B U B' U2 R' 
F R U R2 U F' R2 U R' 
B' R F U' B R U' F' R' 
B' R F U2 B R U' F' R' 
B' R F U B R U' F' R' 
F R' F' U2 R2 F U' F' R' 
B' R B' F R B2 U' F' R' 
U' B' R U' B D2 L2 D2 R' 
U' B' R D B2 D' U' B' R' 
F R2 F' R' U' B U' B' R' 
L U2 L' U B' R U' B R' 
U' R2 B' R U R2 U2 B R' 
F' U B' F U' R U2 B R' 
U' B' R U R2 U2 R2 B R' 
U' B R D2 U' L D2 B R' 
B' L' U' B R U2 L B R' 
B' U' L' B R U2 L B R' 
B' F R2 F' U R' B U' R2 
R' U2 R' B' U R' B U' R2 
R U2 R B' U R' B U' R2 
R2 F U R U2 F' R' U R2 
B' U F R U2 R B F' R2 
R B U B' U2 B' R B R2 
U2 B' U2 R U' B R2 U' R 
F R' U' B' R2 B F' U' R 
B U' B' R' F' U' F U' R 
U' B' R U' B U2 R2 U2 R 
F R' F' U' R2 U R2 U2 R 
B U2 F U B' R' F' U2 R 
R2 U' R2 U F R F' U2 R 
R2 D' F2 D F R F' U2 R 
B U' B' R' D' F' D U2 R 
R' U F' L U' F L' U2 R 
F R B U' F' U2 B' U2 R 
R2 F R' U' R2 U2 F' U R 
F R' U R2 U2 R2 F' U R 
F' R' D2 U L' D2 F' U R 
F L F2 R' U L' F' U R 
F R' D' F2 D U F U R 
R' F2 L F U L' F U R 
F R' U F' D2 L2 D2 U R 
F R' B' U' R2 B U' F' R 
F R' B' U2 R2 B U' F' R 
F R' B' U R2 B U' F' R 
R' B' R F R B U' F' R 
F R' B' R2 B F2 U' F R 
R' D' F' U L' U L D R 
L' R' F' U L' F U L R 
R' D' F' D U L' U L R 
R' F' U L2 F L U L R 
L' R' U' B' R U' B L R 
F R U' B U F' U2 B' R 
R' U' B2 R2 B R' U' B R 
R' U' B2 R2 B U' R' B R 
U' R' B' U R' U2 R' B R 
B U' B' R' U2 B' R2 B R 
R' U2 F' U B' F R B R 
R2 B' R' B R2 F R U' F' 
F' R' F' U2 F' R F2 U' F' 
R F R2 F' U2 R' F U' F' 
R B U2 B' U2 R' F U' F' 
R' U2 F' U2 F R F U' F' 
R' U2 B' R2 B R F U' F' 
F D R' B' R2 B D' U' F' 
L' U2 B L F U' B' U2 F' 
U2 L F' U2 F' L' F' U F' 
F U2 F' L F' L' F2 U F' 
F2 R' F' R F' U2 F U F' 
L U2 B L2 B' L' F U F' 
U2 L' B L' B' L2 F U F' 
L' F' L2 F U2 L F U F' 
L' D' U2 B D L F U F' 
L' U B' U B L F U F' 
U2 B D L D' B' F U F' 
F U2 L F2 L F' L2 U F' 
F L F2 U2 L F L2 U F' 
B' F R' U R2 B U' R' F' 
R2 B' F R' B R2 U' R F' 
F D B' R B U' R D' F' 
U F L F U F U L' F' 
U F L U' F U2 F L' F' 
F U L2 F2 L' U F L' F' 
F U2 F L U' F L' U F2 
B' F R B U' R F R2 F2 
F R' B' R2 B U' F R F2 
F' L B L2 B' U F' L' F2 
R F R2 F' U2 R' F' U' F 
R B U2 B' U2 R' F' U' F 
R' U2 F' U2 F R F' U' F 
R' U2 B' R2 B R F' U' F 
F R2 B' R' B R' F2 U' F 
L2 B F' L' U2 L' B' U' F 
R B U' B' R' U2 F' U2 F 
F' R2 F2 R U2 F' R U F 
L F' R' U2 L' F' R U F 
R' F R U' F' U' F' U F 
F' R2 F2 R U2 F' U R F 
L F' R' U2 L' F' U R F 
L B U F2 L' B' F L' F 
L B U L' F' U' B' L' F 
L B U L' F' U2 B' L' F 
L B U L' F' U B' L' F 
F' U' L' U B' U' B L F 
B2 L2 B' L' U F' L' B' F 
L2 U F' L U' B L2 B' F 
B L U F' L2 U' L B' F 
U' F U2 F2 L U' F U2 L' 
L2 U F' L U' F L' U2 L' 
U L' F' L2 U' F L2 U2 L' 
U L' F' U' L2 F L2 U2 L' 
U L' U' L2 F U F' U L' 
F' L D F2 D' U F' U L' 
U L F2 U' F' U F2 U L' 
F U F L2 F L' F U L' 
U2 B L' B' L U' L U L' 
L2 F' L' F U2 F U' F' L' 
U L U F' U F2 U2 F' L' 
B U B' L U2 F U2 F' L' 
B' U B L U2 F U2 F' L' 
F' L B L2 B' F2 U F' L' 
B' U2 B U2 L F U F' L' 
U L U F U' F2 U' F L' 
U2 F U' F L F U2 F L' 
U L' F' D2 U R2 B' D2 L' 
U L' D F' D2 U B' D L' 
U L' U2 L2 B L2 U' B' L' 
U L U2 B U L2 U2 B' L' 
U B L' D2 F' D2 U B' L' 
U' L B L' U2 L' U B' L' 
U L U2 B U2 L2 U B' L' 
U L' D2 F' U R2 D2 B' L' 
U' L B U' L' U' L' B' L' 
F U F' L B U L' B' L' 
F U F' L U B L' B' L' 
B U B' L U2 B L2 B' L' 
B' U B L U2 B L2 B' L' 
L' U2 B L' B' U' L2 U L2 
B U L' B' L2 F' L F L2 
B L' U L2 F' L B' F L2 
L' U2 B L' B' D' B2 D L2 
L2 U' L B U2 L' U' B' L2 
L' U' B U2 L2 U L B' L2 
U L' B U B2 U B U' L 
L' U2 R B' U R' B U' L 
U L' F' U L2 U2 F U2 L 
B U B' L' F' L2 F U2 L 
B' U B L' F' L2 F U2 L 
L2 U F' L U' F L U2 L 
L' F' L' B' F U' B U2 L 
F' L F L2 B' U' B U2 L 
F' L2 F L B' U' B U2 L 
B U B' L' B' U2 B U2 L 
B' U B L' B' U2 B U2 L 
L' F' L U F' L2 F2 U L 
L' F' U L F' L2 F2 U L 
F U F' L' F' L' F U L 
R' D' F' D R U L' U L 
F R' F R F2 U L' U L 
F L U F' L' F' L' U L 
F U L F' L' F' L' U L 
F' R' F' R U F L' U L 
F' L U' F2 U2 F' L2 U L 
F' L U F' L F2 L U L 
F' U L F' L F2 L U L 
L' B U F' L' B' L' F L 
L' D' R' U' R U' B D L 
L' R' U' R D' U' B D L 
R' U' R U' L' D' B D L 
U B L' B2 U2 B2 U' B' L 
U B' U2 B2 U2 L' U B' L 
U B D2 F2 D2 L' U B' L 
U F' L2 B F L U B' L 
U B L D U L2 D' B' L 
B' U' B U B U L' B' L 
U2 B' U B U' B L' B' L 
F U F' U L2 B L B' L 
U2 F U' F' L2 B L B' L 
U L' U B2 U B' U' B2 L 
U' B' R U' B' L' R' B2 L 
L' U' B' R U' B' R' B2 L 
L' R' U' R' B' R2 U' B L 
R' U' R B R B R' U' B' 
B R B' U' R B2 R2 U' B' 
F R U' B2 R' B' F' U' B' 
F D R D' U' B F' U' B' 
U' B L' U L2 U L' U' B' 
F U' B F' L U L' U' B' 
F' U' B F L U L' U' B' 
U' B L U2 L2 U' L U' B' 
R U' B' R B' R2 B' U' B' 
R' F R' F' R2 U' B U' B' 
F D R D' F' U' B U' B' 
R F R F' U' R' B U' B' 
R F R U' F' R' B U' B' 
R' U' B' R B R B U' B' 
U' B R U2 B2 U' R' U2 B' 
U' B R U' B2 U2 R' U2 B' 
B U' R2 B R' B2 R' U2 B' 
B2 U' R B' U R' B' U2 B' 
B U' B2 R B R' B U2 B' 
F U R U' R' B F' U B' 
F' L' U2 L U' B F U B' 
R' U' R B R B U' R' B' 
B U' R2 B' R' U2 B2 R' B' 
L' U' B R U' L B2 R' B' 
B D L' U F' L' F D' B' 
F U B F' D U L' D' B' 
U2 F U' B F' D L' D' B' 
F U F' U B D L' D' B' 
B D U F' L2 F L D' B' 
L U' L2 B U' L2 U' L' B' 
L' F U2 B U' F' U L' B' 
F U B F L F2 U L' B' 
L' U2 F U2 B U F' L' B' 
U' B U' L2 U' L U L2 B' 
B' U B2 L F' L F L2 B' 
L F U F' U L B L2 B' 
L U2 F U' F' L B L2 B' 
L' U' B L2 U2 L2 U' L B' 
L' D2 U' R2 D2 B U' L B' 
L' U B F' L2 F U L B' 
L' B U F' L2 U' F L B' 
L' B U F' L2 U2 F L B' 
L' B U F' L2 U F L B' 
B2 L' B' U F' L2 F L B' 
L' B' U B2 F' L2 F L B' 
L' U' B' D' U' B2 D L B' 
R' U' R U' B2 L' B' L B' 
L U L2 U2 B' U' B2 L B' 
L B U B' L2 U2 B L B' 
L' U2 L2 U' L2 U B L B' 
L U2 L2 D' B2 D B L B' 
U2 L U' L' U L' B L B' 
U B L' U2 B2 U' B' L B2 
B U' B' U2 B L' B L B2 
R' U' R' B2 R' B R' U' B 
U' B' R2 U R U' R2 U' B 
L F' U2 L' U B' F U' B 
U2 L' B L B' U B' U' B 
U2 R' U R2 B' U R' U2 B 
U' B R U B2 R' B2 U2 B 
B' R' F' U F U' R U B 
F U R U' R' B' F' U B 
F' L' U2 L U' B' F U B 
U' B U' L U' L' B2 U B 
U' B' U R' U' R2 U' R' B 
R' U' R' B2 R' B U' R' B 
R' U' R2 B U2 B2 U R' B 
B2 R B U' F R2 F' R' B 
R B U' B2 F R2 F' R' B 
R U' B D U' B2 D' R' B 
R' U2 F' U F R2 B' R' B 
R' U2 F' U F R' B' R2 B 
F U' B' F' U R' U2 R B 
F' U' B' F U R' U2 R B 
U' B D' R D2 U' L D' B 
U' B R D2 F2 U' L D2 B 
B' L' U' B U2 L' B2 L2 B 
B' U' L' B U2 L' B2 L2 B 
L' U' B D2 R D2 U' L B 
U' B D2 R F2 D2 U' L B 
U' B' U2 L' U2 B2 U' L B 
U B' L' B U2 B U' L B 
U' B U2 B2 L' B2 U L B 
U' B U2 B2 L' U B2 L B 
B U B2 L' B U2 B L B 
R' U' R B' U' L' B L B       
      ''';
final List<String> fourCycleSetupAlgorithms = _rawInput.split('\n').where((element) => element.trim().isNotEmpty).toList();   
