const _rawInput = '''
R2 B' R' B2 U' B' U2 R' U' 
F U F R2 F2 R' U R' U' 
U2 F' U' F U' R U R' U' 
F U' F2 U2 F R U R' U' 
F' L U L' F R U R' U' 
D F' U F D' R U R' U' 
D2 F' U F D2 R U R' U' 
D' F' U F D R U R' U' 
L F' U F L' R U R' U' 
L' F' U F L R U R' U' 
R U F R2 F R' F2 R' U' 
R B U L U L' B' R' U' 
F' U F R B' U B R' U' 
F' U F R U2 R2 U' R U' 
U2 B U B' U2 R' U R U' 
F' U F' R2 F2 R U R U' 
R' U F' R' F' R F R U' 
U2 F' L F L' F U' F' U' 
U' F U' R U2 R' U F' U' 
F R F R' F' R' U F' U' 
R' D' F' D R F U F' U' 
U' F D U R' D' U F' U' 
R' B' R' B U F R F' U' 
R' B' R' U B F R F' U' 
R' U R F D R' D' F' U' 
R' F L R U F' L' F' U' 
R' F R U L F' L' F' U' 
F' U2 L' U' L2 F' L' F2 U' 
U2 F' L F' L' F U' F U' 
U' F' D' U' L D U' F U' 
U' F' U L' U2 L U' F U' 
F' R2 F' R F2 R U F U' 
L' U2 L U' L2 F' L2 F U' 
F' L' B' U B U L F U' 
D F' U F R U R' D' U' 
F' U F D R U R' D' U' 
D2 F' U F R U R' D2 U' 
F' U F D2 R U R' D2 U' 
D' F' U F R U R' D U' 
F' U F D' R U R' D U' 
U2 B' U B U' L U' L' U' 
U2 L U' L F' L' F L' U' 
U2 L' U' L F' L F L' U' 
L U2 L' U' F' L2 F L2 U' 
L U2 L2 U' F' L' F L U' 
U' B D U' L D' U' B' U' 
U2 R' U2 R U' B U2 B' U' 
R B2 R' B2 U' B U2 B' U' 
U' B U' L U2 L' U B' U' 
F' U B F R U R' B' U' 
U' B' U R' U2 R U' B U' 
B2 R B2 R' U' B' U2 B U' 
B R B' R' U' B2 U2 B U' 
U2 R U B' U R' U B U' 
U' B' D' U R' D U B U' 
F' U B' F R U R' B U' 
R' U' B' R2 B R2 U' R' U2 
U B' U' R U' B U' R' U2 
R U' R' B' R B U' R' U2 
U' F' U2 F U' R U2 R' U2 
F' U F2 U' F' R U2 R' U2 
B F' U B' F R U2 R' U2 
B' F' U B F R U2 R' U2 
R B F U B' F' U2 R' U2 
R B' U' B2 U B' U2 R' U2 
R' U R2 F R2 F' U R' U2 
R U2 B F U' B' F' R' U2 
R U2 B' U B2 U' B' R' U2 
R U' R2 B' R2 B U' R U2 
U B U2 B' U R' U2 R U2 
B F U' B' F' R' U2 R U2 
B F' U' B' F R' U2 R U2 
B U' B2 U B R' U2 R U2 
R' F U F2 U' F U2 R U2 
R' B' F' U' B F U2 R U2 
R U F R2 F' R2 U R U2 
U' F U R' U F' U R U2 
R' U R F R' F' U R U2 
R' U2 F U' F2 U F R U2 
R' U2 B' F' U B F R U2 
L' U2 L F' U' F2 U F' U2 
U' L' U' L U' F U F' U2 
L' U2 L B F U B' F' U2 
L U2 L' B' F U' B F' U2 
L' U2 L B' F U B F' U2 
U' R U R' U2 F' U F U2 
U R U' R' U F' U F U2 
U F U F' L F' L' F U2 
U F' U F' L F L' F U2 
L U2 L' B' F' U' B F U2 
U' L' B L B' L U' L' U2 
L' U' L2 B L2 B' U' L' U2 
L B F U B' F' U2 L' U2 
L F U F2 U' F U2 L' U2 
U L F' L F L' U L' U2 
L' U F' L2 F L2 U L' U2 
L U F' L' F L U L' U2 
L U2 B F U' B' F' L' U2 
L U2 F U' F2 U F L' U2 
L' U' B L B' L' U' L U2 
L U' B L2 B' L2 U' L U2 
U' L' B L' B' L U' L U2 
L' B' F' U' B F U2 L U2 
L' B' U' B2 U B' U2 L U2 
L U L2 F' L2 F U L U2 
U L F' L' F L' U L U2 
L' U2 B' F' U B F L U2 
L' U2 B' U B2 U' B' L U2 
U' R' U R U' B U' B' U2 
U R' U' R U2 B U' B' U2 
U' B U' B L' B' L B' U2 
U' B' U' B L' B L B' U2 
U L U L' U B' U' B U2 
L U2 L' B U B2 U' B U2 
B U' B R2 B2 R' U' R' U 
U2 F' U' F U2 R U' R' U 
B U' B' R' U2 R2 U R' U 
R U' B R B R' B' R' U 
U2 B U B' U R' U' R U 
D B U' B' D' R' U' R U 
D2 B U' B' D2 R' U' R U 
D' B U' B' D R' U' R U 
L B U' B' L' R' U' R U 
L' B U' B' L R' U' R U 
B' U B2 U2 B' R' U' R U 
B L' U' L B' R' U' R U 
B' U' B' R2 B2 R U' R U 
R2 F R F2 U F U2 R U 
B U' B' R' F U' F' R U 
R' F' U' L' U' L F R U 
R' U' B' R2 B' R B2 R U 
U2 R' U' F U' R U' F' U 
U F D U' R D' U' F' U 
F' R' F R U F2 U2 F' U 
F2 R' F2 R U F U2 F' U 
U F U' R U2 R' U F' U 
B U' B' F R' U' R F' U 
U F' U L' U2 L U' F U 
U2 R U2 R' U F' U2 F U 
R' F2 R F2 U F' U2 F U 
U F' D' U L' D U F U 
B U' B' F' R' U' R F U 
B U' B' D R' U' R D' U 
D B U' B' R' U' R D' U 
B U' B' D2 R' U' R D2 U 
D2 B U' B' R' U' R D2 U 
B U' B' D' R' U' R D U 
D' B U' B' R' U' R D U 
L' U2 L2 U B L B' L' U 
L' U2 L U B L2 B' L2 U 
U2 F U' F' U L' U L U 
U2 L U L' B L' B' L U 
U2 L' U L' B L B' L U 
B R2 B R' B2 R' U' B' U 
U B D U L' D' U B' U 
U B U' L U2 L' U B' U 
U2 B L' B L B' U B' U 
B L F U' F' U' L' B' U 
L U2 L' U L2 B L2 B' U 
B U2 L U L2 B L B2 U 
U B' U R' U2 R U' B U 
B' R' B' R B R U' B U 
U B' D' U' R D U' B U 
R D B D' R' B' U' B U 
U2 B L' B' L B' U B U 
R F R U' B' F' R' B U 
R F R F' U' B' R' B U 
R U' R' B' D' R D B U 
R B' L' R' U' B L B U 
R B' R' U' L' B L B U 
U R F2 R F' R2 F' U' R' 
U2 R' U' R2 F R2 F' U' R' 
U2 R B F U B' F' U2 R' 
U2 R B U B2 U' B U2 R' 
U2 R' U B' R2 B R2 U R' 
F D R' D' F' U' R U R' 
U2 R U B' R' B R U R' 
U' B' D' R' D B R U R' 
R B R B' R' U' B' U R' 
U' R B R B' R' B' U R' 
U' B' R B F U R' F' R' 
U' B' R B U F R' F' R' 
F D B R B' D' R' F' R' 
B R F2 R' F' U' B' F' R' 
R F2 R' B F' U' B' F' R' 
U2 R U2 B F U' B' F' R' 
R B F U B' F R F2 R' 
B R F2 U R' U' B' F2 R' 
R2 D R' B R' B' R D' R' 
U' B' U B R D B' D' R' 
R B' R' B R D B D' R' 
R2 D' R F' R' F R' D R' 
D' R' F' U' R U F D R' 
B R B' D' F' R' F D R' 
D' R' D B U R U' B' R' 
B R U F R' F' U' B' R' 
B R U F2 R' F2 U' B' R' 
U R B L U' L' U' B' R' 
F U' F' R U B U' B' R' 
F' U' F R U B U' B' R' 
R U' B U R B R' B' R' 
R2 B R' U R' U' R B' R' 
B U' R' U' R U R B' R' 
R B' D B' L B' D' B' R' 
B' D' R2 D R2 B' R' B2 R' 
B R2 U R2 U' B R' B2 R' 
R2 B' D B2 D' B R' B2 R' 
B2 U B' U2 B U R B2 R' 
U B U2 B' U B2 R B2 R' 
B R U R' U' B R B2 R' 
U2 R U2 B U' B2 U B R' 
R2 B' R D' R' D R' B R' 
U' B' L' B' L U R B R' 
U' B' L' B' U L R B R' 
R D B' D' R' B' R B R' 
R B D B L' B D' B R' 
R2 U2 R' D U' B' D' U' R2 
R2 D2 L D' U B D' U' R2 
R2 D' U' F' D U' R' U2 R2 
R2 D U B D' U R U2 R2 
R2 D2 L' D U' F' D U R2 
R2 U2 R D' U F D U R2 
U' R' U2 F' U' F2 R' F' R2 
R' F R' D R' D' R F' R2 
R' F2 R' F D' F2 D F' R2 
R' F' R U' R' U R' F R2 
F' R' F2 D' F' D2 R' D' R2 
R' D R' B R' B' R D' R2 
R D R' B R B' R D' R2 
R2 D U B' D U' L' D2 R2 
R2 D' U' F D' U L D2 R2 
R' D' R F' R' F R' D R2 
R D' R F' R F R' D R2 
B R B2 D B D2 R D R2 
R B R' U R U' R B' R2 
R B' R D' R D R' B R2 
U R U2 B U B2 R B R2 
R B2 R B' D B2 D' B R2 
B' D' R D B U R' U' R 
U2 R' U' F R F' R' U' R 
U F D R D' F' R' U' R 
U2 R U' F R2 F' R2 U' R 
R' F' R' F R U F U' R 
U R' F' R' F R F U' R 
U2 R' F' U' F2 U F' U2 R 
U2 R' B' F' U' B F U2 R 
U2 R U R2 B' R2 B U R 
U' R' B2 R' B R2 B U R 
U2 R' U2 F' U F2 U' F' R 
U F L F L' U' R' F' R 
R' D' F D R F R' F' R 
U F L F U' L' R' F' R 
R2 F R' D R D' R F' R 
R' F' D' F' L F' D F' R 
F2 U' F U2 F' U' R' F2 R 
F' R' U' R U F' R' F2 R 
U' F' U2 F U' F2 R' F2 R 
F' R2 U' R2 U F' R F2 R 
R2 F D' F2 D F' R F2 R 
F D R2 D' R2 F R F2 R 
D R D' F' U' R' U F R 
B U B' R' U' F' U F R 
B' U B R' U' F' U F R 
U' R' F' L' U L U F R 
F' R' U' B2 R B2 U F R 
F' R' U' B' R B U F R 
F' U R U R' U' R' F R 
R2 F' R U' R U R' F R 
R' U F' U' R' F' R F R 
R' F D' F L' F D F R 
F' R' B2 U' R U B2 F R 
U2 R' U2 B' F' U B F R 
R' B2 R B F' U B F R 
F' R' B2 R B U B F R 
R2 D R' B R B' R D' R 
D R B U R' U' B' D' R 
F' R' F D B R B' D' R 
R2 D' R F' R F R' D R 
R' F R F' R' D' F' D R 
U F U' F' R' D' F D R 
R' B' F' U' B' F R' B2 R 
U F R' B' F' U' R B R 
B' D' F' R' F D R B R 
U F R' F' U' B' R B R 
F2 U' R U R' U F' U' F' 
U R U' R F2 R2 F' U' F' 
L' U2 L U2 F' U F2 U' F' 
F2 R' F2 R F' U F2 U' F' 
B F U' B' R' U2 R U2 F' 
F R' U2 F' U F R U2 F' 
F L F U F' U L' U2 F' 
F L U2 F U' F' L' U2 F' 
F R B U B' U' R' U F' 
B F U' B' R' U' R U F' 
F R' U F' U2 F R U F' 
U R U' R' F' U2 F2 U F' 
R B U B' U' R' F U F' 
F2 R' F' R U' R U R' F' 
U F U' R F R F' R' F' 
F U' R U B U' B' R' F' 
B F' U' B F2 R B2 R' F' 
F U' R' F' U2 F U' R F' 
F U2 R' F' U' F U2 R F' 
R' F2 R' F' R2 D R2 D' F' 
R U' R' U F D R D' F' 
R F R D B R' B' D' F' 
F D2 B U' R B' R' D2 F' 
F D2 R B R' U B' D2 F' 
F U2 L F U F' U2 L' F' 
B' F U' B U2 L U2 L' F' 
F U2 L U' F U' F' L' F' 
B L' U2 L U2 F U' B' F' 
B F2 R' F2 R F U' B' F' 
L' U2 L U2 B F U' B' F' 
F2 R' F2 R B F U' B' F' 
F2 R B2 R' B' F' U B' F' 
F' R B2 R' B' F2 U B' F' 
U2 R' U2 R B F U B' F' 
F U2 R' U2 R B U B' F' 
F U' R' U R B U B' F' 
B' F U' B R B2 R' B2 F' 
B' L' U2 L U2 F U' B F' 
B' F2 R' F2 R F U' B F' 
L' U2 L U2 B' F U' B F' 
F2 R' F2 R B' F U' B F' 
L U2 L' U2 B' F U B F' 
B2 R B2 R' B' F U B F' 
F L U2 L' U2 B' U B F' 
B2 F R B2 R' B' U B F' 
F' R' F R F' U F' U' F2 
F' R' F' R F' U F U' F2 
F' U F' U L' U' L U' F2 
F U F U' R U' R' U F2 
B F2 U' B' R' U' R U F2 
R' F2 R U F U2 F' U F2 
F' U F' U2 L' U L U F2 
B F' U' B F' R B2 R' F2 
B F U' B F R B2 R' F2 
F' R' D R' D' R F' R F2 
U' F U2 F' U' R' F2 R F2 
B F U B' F' R' F2 R F2 
B' F U B F' R' F2 R F2 
F U F2 U' F R' F2 R F2 
F R U' R' U R' F R F2 
F2 U' R' U R B U B' F2 
B F U F' R' F2 R B' F2 
B' F U F' R' F2 R B F2 
R' F' R U R U' R' U' F 
U R' U R2 U2 R' F' U' F 
L U R U' L' R' F' U' F 
L2 U R U' L2 R' F' U' F 
L' U R U' L R' F' U' F 
U R B' U' B R' F' U' F 
D U R U' R' D' F' U' F 
D2 U R U' R' D2 F' U' F 
D' U R U' R' D F' U' F 
U B R U' R' B' F' U' F 
U B' R U' R' B F' U' F 
U2 R U2 R' F U F2 U' F 
F2 U L' U L U' F U' F 
F2 U' L' U' L U2 F U' F 
U R' U' R' F2 R2 F U' F 
B F' U' B' R' U2 R U2 F 
F' R' U2 F' U F R U2 F 
F' L F U F' U L' U2 F 
F' L U2 F U' F' L' U2 F 
U F2 L F L2 U L U2 F 
F' R B U B' U' R' U F 
B F' U' B' R' U' R U F 
F' R' U F' U2 F R U F 
R B U B' U' R' F' U F 
F' U' R U B U' B' R' F 
B F U' B F2 R B2 R' F 
R' F2 R' F U' R2 U R2 F 
U F' U' R' F2 R' F R2 F 
F' U' R' F' U2 F U' R F 
F' U2 R' F' U' F U2 R F 
R' F2 R F U' R' U R F 
R' F' U' B2 R' B2 U R F 
R' F' U' B' R' B U R F 
U' F U2 F2 U' R' F' R F 
F2 U F U' F R' F' R F 
R' D B R' B' D' F' R F 
R2 D R D2 F D F2 R F 
F2 U F' U' F R' F R F 
F2 R' F R' D R D' R F 
R' B2 F' U' R' U B2 R F 
R' B' F' U' B' R' B2 R F 
F' D2 B U' R B' R' D2 F 
F' D2 R B R' U B' D2 F 
U R U' R' F' L U' L' F 
F' U2 L F U F' U2 L' F 
B' F' U' B U2 L U2 L' F 
F' U2 L U' F U' F' L' F 
U F' L' U' B' U' B L F 
B U R U' R' F' U' B' F 
B U2 R U2 R' F' U' B' F 
U2 R U2 R' B F' U' B' F 
B2 R' F2 R B' F U' B' F 
B' R' F2 R B2 F U' B' F 
U2 R' U2 R B F' U B' F 
F R B2 R' B' F2 U B' F 
F2 R B2 R' B' F U B' F 
F' U2 R' U2 R B U B' F 
F' U' R' U R B U B' F 
B2 U R U' R' F' U' B2 F 
B' F' U' B R B2 R' B2 F 
B' U R U' R' F' U' B F 
B' U2 R U2 R' F' U' B F 
U2 R U2 R' B' F' U' B F 
B R' F2 R B2 F U' B F 
B2 R' F2 R B F U' B F 
L U2 L' U2 B' F' U B F 
B2 R B2 R' B' F' U B F 
F' L U2 L' U2 B' U B F 
B2 F' R B2 R' B' U B F 
R' F' U' R U F D R' D' 
R' D B U R U' B' R' D' 
D U R U' R' F' U' F D' 
U R U' R' D F' U' F D' 
D U' R' U R B U B' D' 
U' R' U R D B U B' D' 
D2 U R U' R' F' U' F D2 
U R U' R' D2 F' U' F D2 
D2 U' R' U R B U B' D2 
U' R' U R D2 B U B' D2 
R D' F' U' R' U F R D 
R B U R' U' B' D' R D 
D' U R U' R' F' U' F D 
U R U' R' D' F' U' F D 
D' U' R' U R B U B' D 
U' R' U R D' B U B' D 
L F' U F R U R' U' L' 
F' U F L R U R' U' L' 
U2 L U' L' F' L F U' L' 
L D2 R' D' U F' D' U' L' 
U2 L' U' F' L2 F L2 U' L' 
L U' B U' L U' B' U' L' 
U2 L F' U' F2 U F' U2 L' 
U2 L B F U B' F' U2 L' 
L2 U' F U2 F' U L' U2 L' 
U L' F' L F U L2 U2 L' 
U' B L2 B' L2 U' L U2 L' 
B' F U' B F' U2 L U2 L' 
B' F' U' B F U2 L U2 L' 
B' U' B2 U B' U2 L U2 L' 
U L2 F' L2 F U L U2 L' 
U2 B' F U B F' L U2 L' 
U2 B' F' U B F L U2 L' 
U2 B' U B2 U' B' L U2 L' 
B U' B' L R' U' R U L' 
L B U' B' R' U' R U L' 
L U B U L' U B' U L' 
U2 L' U L2 B L2 B' U L' 
U2 L U2 F' U F2 U' F' L' 
U2 L U2 B F U' B' F' L' 
L U R U' R' F' U' F L' 
U R U' L R' F' U' F L' 
L D U F D U' R D2 L' 
L U' R' U R B U B' L' 
U' R' U L R B U B' L' 
F' U F L2 R U R' U' L2 
L2 D2 R' D' U F' D' U' L2 
L2 U2 L D U' F D' U' L2 
L' U2 L' U B' U2 B U' L2 
L2 D U F' D' U L' U2 L2 
L2 D' U' B D U' L U2 L2 
B U' B' L2 R' U' R U L2 
L U2 L U' F U2 F' U L2 
L2 U2 L' D' U B' D U L2 
L2 D2 R D U' B D U L2 
L2 D' U' B' D' U R' D2 L2 
L2 D U F D U' R D2 L2 
L' F' U F R U R' U' L 
F' U F L' R U R' U' L 
L' U' F' U' L U' F U' L 
U2 L U' L2 F' L2 F U' L 
U2 L' B' F' U' B F U2 L 
U' L2 B L2 B' U' L' U2 L 
B F U B' F' U2 L' U2 L 
B' F U B F' U2 L' U2 L 
F U F2 U' F U2 L' U2 L 
U F' L2 F L2 U L' U2 L 
U2 B F U' B' F' L' U2 L 
U2 B' F U' B F' L' U2 L 
U2 F U' F2 U F L' U2 L 
U' L B L' B' U' L2 U2 L 
L2 U B' U2 B U' L U2 L 
U2 L' B U B2 U' B U2 L 
B U' B' L' R' U' R U L 
L' B U' B' R' U' R U L 
L' U F' U L' U F U L 
L' D2 R D U' B D U L 
U2 L U B L2 B' L2 U L 
U2 L' U L B L' B' U L 
L' U R U' R' F' U' F L 
U R U' L' R' F' U' F L 
U2 L' U2 B' F' U B F L 
L' D' U' B' D' U R' D2 L 
L' U' R' U R B U B' L 
U' R' U L' R B U B' L 
U2 L' U2 B U' B2 U B L 
B F' U F R U R' U' B' 
B R U' B U2 B' R' U' B' 
B R' F' U' F U R U' B' 
R' F' U' F U R B U' B' 
B F' U F R U2 R' U2 B' 
B R U2 B U' B' R' U2 B' 
U' B2 L' B' L2 U' L' U2 B' 
B L' B' U' B U' L U2 B' 
B L' U2 B' U B L U2 B' 
R B R' U' R' U R U B' 
U' F R' U R B F' U B' 
U' F' R' U R B F U B' 
B2 U L U L' U2 B' U B' 
B2 U' L U' L' U B' U B' 
U' R U R B2 R2 B' U B' 
U2 R' U2 R B' U' B2 U B' 
U' R U' R2 U2 R B U B' 
U' R' F U F' R B U B' 
L U' R' U L' R B U B' 
L2 U' R' U L2 R B U B' 
L' U' R' U L R B U B' 
D U' R' U R D' B U B' 
D2 U' R' U R D2 B U B' 
D' U' R' U R D B U B' 
R B2 R' B' U R U' R' B' 
R B U F R F' U' R' B' 
R B U F2 R F2 U' R' B' 
B U2 R B U B' U2 R' B' 
B U R B U2 B' U R' B' 
R B F2 U R U' F2 R' B' 
R B F U F R F2 R' B' 
B2 R B' R D' R' D R' B' 
B2 U' B U B' R B' R' B' 
R2 D' R' D2 B' D' B2 R' B' 
U B' U2 B2 U R B R' B' 
B2 U' B' U B' R B R' B' 
R D' F' R F D B R' B' 
R B2 R B' U R2 U' R2 B' 
U' B U R B2 R B' R2 B' 
B' F' U B2 F' R' F2 R B' 
B U R' U' F' U F R B' 
B D2 F' U R' F R D2 B' 
B D2 R' F' R U' F D2 B' 
U' B L U F U F' L' B' 
B F U F' U2 L' U2 L B' 
B U2 L' B' U' B U2 L B' 
U' R' U R B L' U L B' 
B U2 L' U B' U B L B' 
B2 F' U F R U R' U' B2 
B' U' B' U R' U R U' B2 
B U' B U2 L U' L' U' B2 
R B2 R' U' B' U2 B U' B2 
B U' B U' L U L' U B2 
B R B R' B U' B' U B2 
B R B' R' B U' B U B2 
B' R' U R U' R B' R' B2 
U B' U2 B U R B2 R' B2 
B' F U' B F' R B2 R' B2 
B' F' U' B F R B2 R' B2 
B' U' B2 U B' R B2 R' B2 
B R D' R D R' B R' B2 
B' F' U B' F' R' F2 R B2 
B F' U B F' R' F2 R B2 
B' F' U F R U R' U' B 
B' R U' B U2 B' R' U' B 
B' R' F' U' F U R U' B 
R' F' U' F U R B' U' B 
U' R' U R B U2 B2 U' B 
B' F' U F R U2 R' U2 B 
B' R U2 B U' B' R' U2 B 
B' L' B' U' B U' L U2 B 
B' L' U2 B' U B L U2 B 
L U2 L' U2 B U' B2 U B 
B2 R B2 R' B U' B2 U B 
B2 U R' U' R U' B U B 
U' R' U R' B2 R2 B U B 
B' U2 R B U B' U2 R' B 
B' U R B U2 B' U R' B 
B2 R B R' U R' U' R B 
B F' U B2 F' R' F2 R B 
B' U R' U' F' U F R B 
U' B' U R' B' R' B R B 
B' D2 F' U R' F R D2 B 
B' D2 R' F' R U' F D2 B 
R' U R U' B' D' R' D B 
R B2 R B R2 D' R2 D B 
R' B' R' D' F' R F D B 
B' F U F' U2 L' U2 L B 
B' U2 L' B' U' B U2 L B 
B' U2 L' U B' U B L B 
      
      ''';
final List<String> urFlipAlgorithms = _rawInput.split('\n').where((element) => element.trim().isNotEmpty).toList();
