const _rawInput = '''
R' U F' U F R2 U' R' U' 
R' B' U' R2 B R2 U2 R' U' 
R B2 U' B' U B2 U R' U' 
R' U2 R2 F R2 U' F' R' U' 
R U2 F U2 R2 U F' R' U' 
R' D2 B' L2 D2 U F' R' U' 
R' U2 R2 F U' R2 F' R' U' 
R' B' D2 L2 U F' D2 R' U' 
R' D B' D2 U F' D R' U' 
R U' B U B2 U B R' U' 
R' B' U R2 U2 B U2 R U' 
R' B' U2 R2 U B U2 R U' 
R' F' U2 F2 U F' U R U' 
R' F U' F2 U' F U R U' 
R' U F2 U F' U' F2 R U' 
U2 F' D' L D F2 U' F' U' 
U2 F L F2 U L' U2 F' U' 
U2 F L U F2 L' U2 F' U' 
U2 F U' R U' R' U F' U' 
R B' U R B F R2 F' U' 
U2 F' U' F2 D R D' F' U' 
U2 F' U L' U' L U' F U' 
L' U2 L2 F' U L' U2 F U' 
F' R' F U2 F U' R F U' 
U2 F' U2 R' U F2 R F U' 
F' R' U F U F R F U' 
R B' U R' U2 B2 U2 B' U' 
B R U' B U2 B R' B' U' 
B2 R B' U' B2 U2 R' B U' 
R' B' D2 U F' D2 R' B U' 
R B' U' B2 U2 B2 R' B U' 
R B' D' R2 D U R B U' 
R B' U R' D2 F2 D2 B U' 
F' U B' F R B U2 R' U2 
B' R' B U F' U F R' U2 
B' R F R2 F' U B R' U2 
B' F R' F' U R' B R2 U2 
B' R U' B U2 R2 U R U2 
F R' B' F' R' U B R U2 
F U R' F R F' U2 F' U2 
U F U' R U R' U F' U2 
R U R2 F' U F2 R F' U2 
U F U2 L F2 U' L' F' U2 
F U' L F' U2 F' L' F' U2 
U F U2 L U' F2 L' F' U2 
U F' U L' U L U' F U2 
U F' R' F2 U' R U2 F U2 
R U R2 F R F2 U F U2 
U F D R' D' F2 U F U2 
U F U F2 D' L' D F U2 
L' U' L2 U2 F' U L' F U2 
L F' U' B L2 B' L' F U2 
F' U' L' B L' B' L2 F U2 
L B' U' B U' F' L F U2 
L2 F' L U' B L B' F U2 
U' L' D' B D L2 U' L' U2 
B' U' B2 L' B' L2 U' L' U2 
B L' B2 U' B L2 U' L' U2 
U' L B L2 U B' U2 L' U2 
U' L B U L2 B' U2 L' U2 
U' L U' F U' F' U L' U2 
F U F' U2 F' L F L' U2 
U' L' U' L2 D F D' L' U2 
U' L' U B' U' B U' L U2 
U' L' U2 F' U L2 F L U2 
B U2 B L' B' L U' B' U2 
R B' R' B U2 B U' B' U2 
B R B U2 B R' U B' U2 
L' F' U' L B F L B' U2 
L U2 F' L' B' F U' B U2 
B' R2 F R F' R U B U2 
R' B' R' U' R' U' B R U 
R' B' U R' U2 R' B R U 
R' U2 F U' R F2 U2 F U 
U2 L U' F U F' U L' U 
U2 L U2 B L2 U' B' L' U 
L B L' U2 L' U B' L' U 
U2 L U2 B U' L2 B' L' U 
L' B U2 L2 U L B' L2 U 
U2 L' U B' U B U' L U 
U2 L' F' L2 U' F U2 L U 
U2 L D F' D' L2 U L U 
U2 L U L2 D' B' D L U 
B R U' B2 U2 R' U2 B' U 
B L' U' L2 U' L' U B' U 
B U' L2 U' L U L2 B' U 
R B2 L' R' B' U' L B' U 
L U2 L2 U2 B U' L B' U 
L' D2 R2 D2 B U' L B' U 
L' B L2 U2 L2 U L B' U 
L' B' D' U' B2 D L B' U 
B' R2 U R U' R2 U' B U 
B U B2 R' U' R U' B U 
B R B2 U R' B2 U2 B U 
B R U B2 R' B2 U2 B U 
B' U' R' U R2 U R' B U 
B' U' R U' R2 U2 R B U 
B D' R D2 U' L D' B U 
B R D2 U' F2 L D2 B U 
L' B D2 R D2 U' L B U 
B' U2 L' U2 B2 U' L B U 
B' U2 L' U' B2 U2 L B U 
B U2 B2 L' B2 U L B U 
B D2 R U' F2 D2 L B U 
U2 F' U' F2 R' F' R2 U' R' 
U2 F R' F2 U' F R2 U' R' 
R2 B' R' B R' U R U' R' 
B' U R B F R2 F' U' R' 
B' D' R2 D U R B U' R' 
U R F U' R2 U2 F' U2 R' 
U R B' U' B2 U' B' U R' 
B' R B' D L B' D' B' R' 
U R U' B2 U' B U B2 R' 
U' B L' U B L R B2 R' 
B' R2 D' R' D2 B' D' B2 R' 
B' R2 D B' D2 R' D B2 R' 
U F R2 B' F' R' U' B R' 
U B U2 B2 U2 R U' B R' 
U B' D2 F2 D2 R U' B R' 
U B' R B2 U2 B2 U B R' 
F U F R2 B' F2 R' B R' 
R2 U R2 B U' B2 R' B R' 
R2 B' D B' D' B R' B R' 
B U' B' U2 B' U' R B R' 
U2 B U B' U2 B' R B R' 
U B' R' D' U' R2 D B R' 
R' F' U2 F R' U R2 U' R2 
R' B' R2 B R' U R2 U' R2 
R B' R B2 U B' R2 U' R2 
B2 R B R U B R2 U' R2 
B2 R B R U R2 B U' R2 
R2 B' U R' B U R2 U2 R2 
R' F' U2 F R' D B2 D' R2 
R' B' R2 B R' D B2 D' R2 
R2 U2 R2 U' B' R U' B R2 
R U R' U' R B' R B R2 
R B' R B' D B D' B R2 
B' R B U2 R' U' R' U' R 
B U' B2 U2 R B R2 U' R 
U R' F2 U F U' F2 U' R 
U R U R2 F' U' F U' R 
R' B2 R2 B U R' B U' R 
U R F R2 U F' R2 U2 R 
U R F U R2 F' R2 U2 R 
U' F' U2 F2 R' U F' U2 R 
U R' U' F' U F2 U F' R 
F' U B' F' R B R2 F2 R 
F' U F' R' B' R2 B F2 R 
R2 U R2 U' R F' U2 F R 
R2 D B2 D' R F' U2 F R 
U R' U' F U' F2 U2 F R 
F' U R2 B' R' B R2 F R 
F' R' U B' R U B F R 
F' U2 R' B' U' R B F R 
F' U2 R' U' B' R B F R 
F' U' R' U2 B' R B F R 
U R D' F D2 U' B D' R 
U R F D2 U' L2 B D2 R 
R' U B' R U' B' R2 B2 R 
U R' U2 B' U2 R2 U' B R 
U' R' B' R U2 R U' B R 
U B' R D2 F D2 U' B R 
U R' U2 B' U' R2 U2 B R 
U R U2 R2 B' R2 U B R 
R2 U R2 U' R B' R2 B R 
R2 D B2 D' R B' R2 B R 
U' R' B' U R U R B R 
U R D2 F U' L2 D2 B R 
F R U2 B U2 B' R' U' F' 
F R' F' U2 F U2 R U' F' 
U2 F U2 F R' F' R U' F' 
F U2 L R' F L' R U' F' 
R B' R B F2 R2 F' U' F' 
F2 R B' R B R2 F' U' F' 
B' F2 D' R' D B F' U' F' 
F' R D2 B' D2 R' F2 U' F' 
F' D2 R B' R' D2 F2 U' F' 
U2 L F' L' F U2 F U' F' 
F2 R' F U2 F R F U' F' 
L' B U2 L U2 B' F U' F' 
F L U R' F' L' R U2 F' 
F U L R' F' L' R U2 F' 
B' F R' U2 R2 B R' U F' 
B L U2 L' U2 B' F U F' 
B' U2 R' U2 R B F U F' 
U2 F L F U2 F L' U F' 
B F R B2 R' U2 B' U F' 
B R B2 R' F U2 B' U F' 
B F L U2 L' U2 B' U F' 
F L' B L2 U2 L' B' U F' 
B' F U2 R' U2 R B U F' 
B' F U2 L' B2 L B U F' 
F U R B U2 B' U2 R' F' 
F' U F2 R D2 B D2 R' F' 
F U R' U2 F' U2 F R F' 
U2 R' B' U' R B F R F' 
F' U F2 D2 R B R' D2 F' 
F U2 L R' F R U' L' F' 
B F U2 L' B' L2 U L' F' 
F U' B L U2 L2 B' L F' 
F L U' L2 B L U2 B' F' 
F U' B U2 R B2 R' B' F' 
F U' B U2 L U2 L' B' F' 
F U' B' R' U2 R U2 B F' 
F U' B' L' B2 L U2 B F' 
F U' R B' R2 U2 R B F' 
U2 R2 B' R U' F R B F' 
F U F R2 B' R' B R' F2 
F U F' R' F' U2 F' R F2 
F U B' F D' R D B F2 
F' R U2 B U2 B' R' U' F 
R' F' R2 B' R B R2 U' F 
F' R' F' U2 F U2 R U' F 
F' U2 L R' F L' R U' F 
U2 R U2 B' R' B F' U' F 
F R D2 B' D2 R' F2 U' F 
F D2 R B' R' D2 F2 U' F 
R' B' F2 R2 B R F U' F 
R' F2 R2 B' R' B F U' F 
R' B' F' R' B U R U2 F 
F' L U R' F' L' R U2 F 
F' U L R' F' L' R U2 F 
R' B' F' R' U B R U2 F 
B' D' R' D F' U B U2 F 
B' F' R' U2 R2 B R' U F 
R' B' F' R' B U2 R U F 
B L U2 L' U2 B' F' U F 
B' U2 R' U2 R B F' U F 
L U2 B L' B' F' L' U F 
U2 F' L2 B L B' L U F 
B F' R B2 R' U2 B' U F 
B R B2 R' F' U2 B' U F 
B F' L U2 L' U2 B' U F 
F' L' B L2 U2 L' B' U F 
L U2 F' L B L2 B' U F 
B' F' U2 R' U2 R B U F 
B' F' U2 L' B2 L B U F 
F' U R B U2 B' U2 R' F 
F U F2 R D2 B D2 R' F 
U F' R' F' U' F' U' R F 
R' B' F' U' R' B U' R F 
U F' R' U F' U2 F' R F 
F' U R' U2 F' U2 F R F 
F U F2 D2 R B R' D2 F 
F' U2 L R' F R U' L' F 
B F' U2 L' B' L2 U L' F 
L U2 B F' L' B' U L' F 
F' U' B L U2 L2 B' L F 
F' L U' L2 B L U2 B' F 
F' U' B U2 R B2 R' B' F 
F' U' B U2 L U2 L' B' F 
F' U' B' R' U2 R U2 B F 
F' U' B' L' B2 L U2 B F 
F' U' R B' R2 U2 R B F 
F' U' B L2 B' L' F U2 L' 
B' U' B F' U' L F U2 L' 
B' U' B U' F' L F U2 L' 
U2 B' U B F' L F U2 L' 
F' L U' B L B' F U2 L' 
U' B L' U B' U2 L2 U2 L' 
F' U' L B F L B' U2 L' 
U2 F' L B L2 B' U F L' 
L' U' L2 B U' L U2 B' L' 
U' L B U' L U2 L B' L' 
U2 F' L' F U B' U B L' 
L2 B U2 L' U B' L2 U L2 
B L2 U2 L U L2 B' U L2 
B L2 U2 L2 U L B' U L2 
U2 B F' L' B' U L' F L2 
L2 U' L2 B U' L U2 B' L2 
U F' U2 L U' F L2 U2 L 
U2 F' L U' F U2 L2 U L 
L B U2 L' U B' L2 U L 
U2 B L' B' F' L' U F L 
U' B L' U B' D2 R2 D2 L 
F U B F' U2 L' U2 B' L 
U' L2 B L' U' L2 U2 B' L 
U' B' L' D2 U R' D2 B' L 
U' B L' U' L2 U2 L2 B' L 
U' B L' D' B2 D U B L 
U' B' U R' U R B2 U' B' 
U2 B U L' B L B' U2 B' 
U' B' L' U' B2 L B2 U2 B' 
B L U2 L' B' U' B U2 B' 
U' B L2 U' L' U L2 U B' 
R' U R2 B' R' U2 B2 U B' 
R B' R' U B U2 B U B' 
U' B' U2 B2 R B2 U' R' B' 
U' B' D2 L' F2 D2 U R' B' 
U B R B' U2 B' U R' B' 
U' B U2 R U2 B2 U R' B' 
U2 B U' R B' U2 B' R' B' 
U' B' U2 B2 R U' B2 R' B' 
F U' B U2 F' R B2 R' B' 
F' U' B U2 F R B2 R' B' 
B2 U' B2 U B' R B2 R' B' 
B2 D' R2 D B' R B2 R' B' 
U' B' L' D2 F2 U R' D2 B' 
U' B' D L' D2 U R' D B' 
F U' B F' U2 L U2 L' B' 
F' U' B F U2 L U2 L' B' 
B U2 B' U B L U2 L' B' 
L2 U' B L2 U' L' U2 L2 B' 
L2 U' B L' U' L2 U2 L2 B' 
U' B U' L U L2 U L B' 
U2 L U L2 B' U B2 L B' 
B R B2 R' B U' B2 U B2 
B' R B' R D' R' D R' B2 
R2 U B' R2 U' R' B' R' B2 
R2 U R2 B' U' R' B' R' B2 
B' U' B U B' R B' R' B2 
U B' R U2 B2 U B R' B2 
B R B2 R' B D' R2 D B2 
R U F R2 B' F' R' U' B 
F U' B' F' R' U2 R U2 B 
F' U' B' F R' U2 R U2 B 
U' B' L' U B2 U2 L U2 B 
U' B' L' U2 B2 U L U2 B 
U' B' R' U2 R2 U R' U B 
U' B' R U' R2 U' R U B 
L U2 F' L' U B' F U B 
B2 R B R' B U' B' U B 
L U2 F' L' F U B' U B 
U2 L U L2 B L B2 U B 
U2 R' U' R2 U2 B' U R' B 
U2 R B' U' F R2 F' R' B 
R' U R U R U2 B' R' B 
B2 R D' R D R' B R' B 
R B D B L' D' B R' B 
U' B' U R2 U R' U' R2 B 
U2 B' U' R' F R' F' R2 B 
R B2 D' R D2 B D' R2 B 
R B2 D B D2 R D R2 B 
U2 R F' U' F U' B' R B 
R U B' R' D' U' R2 D B 
F' U2 B' U' F D' R D B 
      
      ''';
final List<String> urbuFlipAlgorithms = _rawInput.split('\n').where((element) => element.trim().isNotEmpty).toList();
