name: revenge_cube
description: "A new Flutter package project."
version: 0.0.1
homepage:
  

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  coverage: ^1.11.1
  cube_core:
    path: ../cube_core
  collection: ^1.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:

